Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2018-09, with the labels that each got.

#948 fix(constants): redirect to guide homepage
  client/components/docs/docs.constants.js
Labels: bug, quality check

#951 fix(pci storage): set good links for us storage links
  client/app/cloud/project/storage/storage-add/storage/step_container_type/add-storage-step-container-type.html
  client/app/config/US/common.constants.js
Labels: bug, quality check done

#960 fix(openstack): download rclone config
  client/app/cloud/project/openstack/users/rclone/openstack-users-rclone.modal.controller.js
Labels: bug

#966 fix(ldp): get the list of shareable objects
  client/app/dbaas/logs/detail/aliases/logs-aliases.service.js
  client/app/dbaas/logs/detail/dashboards/logs-dashboards.service.js
  client/app/dbaas/logs/detail/index/logs-index.service.js
  client/app/dbaas/logs/detail/roles/logs-roles.service.js
  client/app/dbaas/logs/detail/streams/logs-streams.service.js
Labels: enhancement, quality check

#955 fix: lint some html files
  client/app/cda/details/home/detail/edit/cda-detail-edit.html
  client/app/cda/pool/add/cda-pool-add.html
  client/app/cda/pool/delete/cda-pool-delete.html
  client/app/cda/user/add/cda-user-add.html
  client/app/cda/user/details/permissions/edit/cda-user-details-permission-list-edit.html
  client/app/cloud/offer/cloud-offer.html
  client/app/cloud/project/add/cloud-project-add.html
  client/app/cloud/project/billing/rights/cloud-project-billing-rights.html
  client/app/cloud/project/compute/infrastructure/diagram/cloud-project-compute-infrastructure-diagram.html
  client/app/cloud/project/compute/infrastructure/ip/failover/buy/cloud-project-compute-infrastructure-ip-failover-buy-agora.html
  client/app/cloud/project/compute/infrastructure/virtualMachine/loginInformation/cloud-project-compute-infrastructure-virtual-machine-login-information.html
  client/app/cloud/project/compute/infrastructure/volume/addEdit/cloud-project-compute-infrastructure-volume-addEdit.html
  client/app/cloud/project/compute/snapshot/add/cloud-project-compute-snapshot-add.html
  client/app/cloud/project/compute/ssh/cloud-project-compute-ssh.html
  client/app/cloud/project/openstack/users/openrc/openstack-users-openrc.html
  client/app/cloud/project/openstack/users/openstack-users.html
  client/app/cloud/project/storage/storage-add/storage/add-storage.html
  client/app/cloud/project/storage/storage-add/storage/step_region/add-storage-step-region.html
  client/app/cloud/project/storage/storage-details/storage-details.html
  client/app/cloud/project/storage/storage.html
  client/app/dbaas/ts/project/add/dbaasts-project-add.html
  client/app/dbaas/ts/project/details/key/addOrEdit/dbaasts-project-details-key-add-or-edit.html
  client/app/deskaas/deskaas-change-username/deskaas-change-username.html
  client/app/deskaas/deskaas-confirm-terminate/deskaas-confirm-terminate.html
  client/app/iplb/modal/nat-ip/iplb-nat-ip-detail.html
  client/app/nasha/add/nasha-add.html
  client/app/nasha/add/nasha-unavailable.html
  client/app/nasha/information/nasha-information.html
  client/app/nasha/partition/custom-snapshot/add/nasha-partition-custom-snapshot-add.html
  client/app/ui-components/agreement/agreement.component.html
  client/app/vps/modal/backup-storage/add-backup-storage.html
  client/app/vps/vps-detail.html
  client/app/vrack/vrack.html
  client/components/cloud-ui/search/search.html
  client/components/cloud/project/billing/instance-list/billing-instance-list.component.html
  client/components/ovh-task-alert/modal/ovh-task-follow-modal.html
  client/components/runabove/promise-task-state/promise-task-state.html
Labels: bug

#958 Fix/vps snapshot option
  client/app/vps/import/vps.service.js
  client/app/vps/snapshot-order/vps-snapshot-order.controller.js
Labels: bug, quality check done

#978 chore: replace eslint-config-ovh by eslint-config-airbnb-base
  .eslintrc
  client/.eslintrc.json
  package.json
  yarn.lock
Labels: enhancement

#980 fix(common): apply eslint rules
  .eslintrc
  client/app/common/OvhPoll.service.js
  client/app/common/cloud-main-controller.controller.js
  client/app/common/cloud-message.service.js
  client/app/common/cloud-navigation.service.js
  client/app/common/cloud-poll.service.js
  client/app/common/phone.constant.js
Labels: bug

#981 fix(config): apply eslint rules
  client/app/config/all.js
  client/app/config/dev.js
  client/app/config/prod.js
Labels: bug

#982 fix(dbaas.dbaass-metrics): apply eslint rules
  .eslintrc
  client/app/dbaas/dbaas-metrics/dashboard/chart-pie/metrics-chart-pie.component.js
  client/app/dbaas/dbaas-metrics/dashboard/metrics-dashboard.controller.js
  client/app/dbaas/dbaas-metrics/dashboard/metrics-dashboard.html
  client/app/dbaas/dbaas-metrics/header/metrics-header.controller.js
  client/app/dbaas/dbaas-metrics/metrics-detail.controller.js
  client/app/dbaas/dbaas-metrics/metrics.constant.js
  client/app/dbaas/dbaas-metrics/metrics.js
  client/app/dbaas/dbaas-metrics/metrics.service.js
  client/app/dbaas/dbaas-metrics/platform/metrics-platform.controller.js
  client/app/dbaas/dbaas-metrics/token/add/metrics-token-add.controller.js
  client/app/dbaas/dbaas-metrics/token/add/metrics-token-add.html
  client/app/dbaas/dbaas-metrics/token/delete/metrics-token-delete.controller.js
  client/app/dbaas/dbaas-metrics/token/edit/metrics-token-edit.controller.js
  client/app/dbaas/dbaas-metrics/token/metrics-token.controller.js
  client/app/dbaas/dbaas-metrics/token/metrics-token.html
  client/app/dbaas/dbaas-metrics/token/preview/metrics-token-preview.controller.js
  client/app/dbaas/dbaas-metrics/token/preview/metrics-token-preview.html
Labels: bug

#984 fix(dbaas.ts): apply eslint rules
  client/app/dbaas/ts/dbaasts.constants.js
  client/app/dbaas/ts/dbaasts.js
  client/app/dbaas/ts/project/add/dbaasts-project-add.controller.js
  client/app/dbaas/ts/project/add/dbaasts-project-add.js
  client/app/dbaas/ts/project/dbaasts-project.controller.js
  client/app/dbaas/ts/project/dbaasts-project.js
  client/app/dbaas/ts/project/dbaasts-project.service.js
  client/app/dbaas/ts/project/delete/dbaasts-project-delete.controller.js
  client/app/dbaas/ts/project/details/billing/dbaasts-project-details-billing.controller.js
  client/app/dbaas/ts/project/details/billing/dbaasts-project-details-billing.js
  client/app/dbaas/ts/project/details/dbaasts-project-details.controller.js
  client/app/dbaas/ts/project/details/dbaasts-project-details.js
  client/app/dbaas/ts/project/details/key/addOrEdit/dbaasts-project-details-key-add.controllers.js
  client/app/dbaas/ts/project/details/key/addOrEdit/dbaasts-project-details-key-add.js
  client/app/dbaas/ts/project/details/key/dbaasts-project-details-key.controller.js
  client/app/dbaas/ts/project/details/key/dbaasts-project-details-key.js
  client/app/dbaas/ts/project/details/key/example/tokens-example-key-controller.js
  client/app/dbaas/ts/project/details/quota/dbaasts-project-details-quota.controller.js
  client/app/dbaas/ts/project/details/quota/dbaasts-project-details-quota.js
  client/app/dbaas/ts/project/details/settings/dbaasts-project-details-settings.controller.js
  client/app/dbaas/ts/project/details/settings/dbaasts-project-details-settings.js
  client/app/dbaas/ts/sidebar/sidebar-edit/dbaasts-sidebar-edit.controller.js
  client/app/dbaas/ts/sidebar/sidebar-edit/dbaasts-sidebar-edit.service.js
Labels: bug

#985 fix(dbaas): apply eslint rules
  client/app/dbaas/dbaas.js
Labels: bug

#989 fix(home): apply eslint rules
  client/app/home/announcement/announcement-summit.config.js
  client/app/home/announcement/announcement-summit.controller.js
  client/app/home/home.controller.js
  client/app/home/home.controller.spec.js
  client/app/home/home.js
Labels: bug

#991 fix(iplb.frontends): apply eslint rules
  client/app/iplb/frontends/delete/iplb-frontends-delete.controller.js
  client/app/iplb/frontends/iplb-frontends-edit.controller.js
  client/app/iplb/frontends/iplb-frontends-edit.html
  client/app/iplb/frontends/iplb-frontends.controller.js
  client/app/iplb/frontends/iplb-frontends.js
  client/app/iplb/frontends/iplb-frontends.service.js
  client/app/iplb/frontends/preview/iplb-frontends-preview.controller.js
Labels: bug

#1000 fix(iplb.vrack): apply eslint rules
  client/app/iplb/vrack/common/iplb-vrack-helper.service.js
  client/app/iplb/vrack/iplb-vrack-edit.controller.js
  client/app/iplb/vrack/iplb-vrack.controller.js
  client/app/iplb/vrack/iplb-vrack.js
  client/app/iplb/vrack/iplb-vrack.service.js
Labels: bug

#990 fix(iplb.configuration): apply eslint rules
  client/app/iplb/configuration/iplb-configuration.controller.js
  client/app/iplb/configuration/iplb-configuration.html
  client/app/iplb/configuration/iplb-configuration.js
  client/app/iplb/configuration/iplb-configuration.service.js
Labels: bug

#992 fix(iplb.graph): apply eslint rules
  client/app/iplb/graph/iplb-graph.controller.js
  client/app/iplb/graph/iplb-graph.js
Labels: bug

#1001 fix(iplb.zone): apply eslint rules
  client/app/iplb/zone/iplb-zone-add.controller.js
  client/app/iplb/zone/iplb-zone-add.service.js
  client/app/iplb/zone/iplb-zone-delete.controller.js
  client/app/iplb/zone/iplb-zone-delete.service.js
  client/app/iplb/zone/iplb-zone.js
  client/app/iplb/zone/iplz-zone-picker.component.js
Labels: bug

#1002 fix(iplb): apply eslint rules
  client/app/iplb/frontends/iplb-frontends-edit.controller.js
  client/app/iplb/iplb-action.service.js
  client/app/iplb/iplb-cipher.service.js
  client/app/iplb/iplb-detail.controller.js
  client/app/iplb/iplb-failover-ip.service.js
  client/app/iplb/iplb-metrics.service.js
  client/app/iplb/iplb-nat-ip.service.js
  client/app/iplb/iplb-zone.service.js
  client/app/iplb/iplb.constants.js
  client/app/iplb/iplb.js
Labels: bug

#1003 fix(nasha.add): apply eslint rules
  client/app/nasha/add/nasha-add.controller.js
  client/app/nasha/add/nasha-add.js
  client/app/nasha/add/nasha-add.service.js
  client/app/nasha/add/nasha-unavailable.controller.js
Labels: bug

#1004 fix(nasha.order): apply eslint rules
  client/app/nasha/order/nasha-order-complete.controller.js
  client/app/nasha/order/nasha-order-complete.js
Labels: bug

#1005 fix(nasha.partition): apply eslint rules
  client/app/nasha/partition/access/add/nasha-partition-access-add.controller.js
  client/app/nasha/partition/access/delete/nasha-partition-access-delete.controller.js
  client/app/nasha/partition/access/nasha-partition-access.controller.js
  client/app/nasha/partition/access/nasha-partition-access.js
  client/app/nasha/partition/add/nasha-partition-add.controller.js
  client/app/nasha/partition/custom-snapshot/add/nasha-partition-custom-snapshot-add.controller.js
  client/app/nasha/partition/delete/nasha-partition-delete.controller.js
  client/app/nasha/partition/nasha-partition.controller.js
  client/app/nasha/partition/nasha-partition.js
  client/app/nasha/partition/snapshot/nasha-partition-snapshot.controller.js
  client/app/nasha/partition/update/nasha-partition-update.controller.js
  client/app/nasha/partition/zfs-options/nasha-partition-zfs-options.constant.js
  client/app/nasha/partition/zfs-options/nasha-partition-zfs-options.controller.js
  client/app/nasha/partition/zfs-options/nasha-partition-zfs-options.service.js
Labels: bug

#1006 fix(nasha): apply eslint rules
  client/app/nasha/nasha.controller.js
  client/app/nasha/nasha.js
Labels: bug

#1007 fix(ui-components): apply eslint rules
  client/app/ui-components/accordion/accordion.component.js
  client/app/ui-components/advanced-options/advanced-options.component.js
  client/app/ui-components/agreement/agreement.component.js
  client/app/ui-components/dropdown-menu/dropdown-menu.component.js
  client/app/ui-components/dual-list/dual-list.component.js
  client/app/ui-components/dual-list/dual-list.controller.js
  client/app/ui-components/dual-list/dual-list.filter.js
  client/app/ui-components/dual-list/dual-list.provider.js
  client/app/ui-components/format-si/format-si.filter.js
  client/app/ui-components/guide-component/guide-component.component.js
  client/app/ui-components/guide-component/guide-component.html
  client/app/ui-components/inline-adder/inline-adder-group.controller.js
  client/app/ui-components/inline-adder/inline-adder.component.js
  client/app/ui-components/inline-adder/inline-adder.controller.js
  client/app/ui-components/input/compare-to.component.js
  client/app/ui-components/input/password.component.js
  client/app/ui-components/message/message-container.component.js
  client/app/ui-components/message/message-container.html
  client/app/ui-components/modal/confirmation-modal/confirmation-modal.controller.js
  client/app/ui-components/modal/info-modal/info-modal.controller.js
  client/app/ui-components/modal/modal.component.js
  client/app/ui-components/modal/name-change-modal/name-change-modal.controller.js
  client/app/ui-components/modal/warning-modal/warning-modal.controller.js
  client/app/ui-components/page/page-content.component.js
  client/app/ui-components/page/page-header.component.js
  client/app/ui-components/tabs/tabs.component.js
  client/app/ui-components/tabs/tabs.service.js
Labels: bug

#1011 fix(veeam): apply eslint rules
  client/app/veeam/veeam-detail.controller.js
  client/app/veeam/veeam.js
  client/app/veeam/veeam.service.js
Labels: bug

#1012 fix(vps.additional-disk): apply eslint rules
  client/app/vps/additional-disk/order/additional-disk-option.filter.js
  client/app/vps/additional-disk/order/vps-order-additional-disk.controller.js
  client/app/vps/additional-disk/vps-additional-disk.controller.js
Labels: bug

#1013 fix(vps.backup-storage): apply eslint rules
  client/app/vps/backup-storage/order/vps-order-backup-storage.controller.js
  client/app/vps/backup-storage/vps-backup-storage.controller.js
Labels: bug

#1014 fix(vps.dashboard): apply eslint rules
  client/app/vps/dashboard/vps-dashboard.controller.js
  client/app/vps/dashboard/vps-dashboard.html
  client/app/vps/dashboard/vps-tile-status.directive.js
Labels: bug

#1015 fix(vps.import): apply eslint rules
  client/app/vps/import/notification.service.js
  client/app/vps/import/vps.constants.js
  client/app/vps/import/vps.service.js
Labels: bug

#1016 fix(vps.modal): apply eslint rules
  .eslintrc
  client/app/vps/modal/backup-storage/add-backup-storage.controller.js
  client/app/vps/modal/backup-storage/delete-backup-storage.controller.js
  client/app/vps/modal/backup-storage/edit-backup-storage.controller.js
  client/app/vps/modal/backup-storage/password-backup-storage.controller.js
  client/app/vps/modal/option/vps-option-terminate.controller.js
  client/app/vps/modal/secondary-dns/add-secondary-dns.controller.js
  client/app/vps/modal/secondary-dns/delete-secondary-dns.controller.js
  client/app/vps/modal/shortcut/display-ips/vps-display-ips.controller.js
  client/app/vps/modal/shortcut/kvm/kvm.directive.js
  client/app/vps/modal/shortcut/kvm/vps-kvm.controller.js
  client/app/vps/modal/shortcut/monitoring-sla/vps-monitoring-sla.controller.js
  client/app/vps/modal/shortcut/password/vps-password.controller.js
  client/app/vps/modal/shortcut/reboot/vps-reboot.controller.js
  client/app/vps/modal/shortcut/reinstall/vps-reinstall.controller.js
  client/app/vps/modal/shortcut/reinstall/vps-reinstall.html
  client/app/vps/modal/shortcut/reinstall/vps-reinstall.service.js
  client/app/vps/modal/shortcut/reverse-dns/vps-reverse-dns.controller.js
  client/app/vps/modal/snapshot/snapshot-delete.controller.js
  client/app/vps/modal/snapshot/snapshot-restore.controller.js
  client/app/vps/modal/snapshot/snapshot-take.controller.js
  client/app/vps/modal/veeam/mount/vps-mount.controller.js
  client/app/vps/modal/veeam/restore/vps-restore.controller.js
Labels: bug

#1018 fix(vps.secondary-dns): apply eslint rules
  client/app/vps/secondary-dns/vps-secondary-dns.controller.js
Labels: bug

#1020 fix(vps.upgrade): apply eslint rules
  client/app/vps/upgrade/vps-upgrade.controller.js
Labels: bug

#1021 fix(vps.veeam): apply eslint rules
  client/app/vps/veeam/order/vps-order-veeam.controller.js
  client/app/vps/veeam/vps-veeam.controller.js
Labels: bug

#1022 fix(vps.windows-order): apply eslint rules
  client/app/vps/windows-order/vps-windows-order.controller.js
Labels: bug

#1017 fix(vps.monitoring): apply eslint rules
  client/app/vps/monitoring/vps-monitoring.constant.js
  client/app/vps/monitoring/vps-monitoring.controller.js
Labels: bug

#1019 fix(vps.snapshot-order): apply eslint rules
  client/app/vps/snapshot-order/vps-snapshot-order.controller.js
Labels: bug

#1023 fix(vps): apply eslint rules
  client/app/vps/vps-action.service.js
  client/app/vps/vps-detail.controller.js
  client/app/vps/vps-header.controller.js
  client/app/vps/vps-task.service.js
  client/app/vps/vps.js
Labels: bug

#1024 fix(vrack): apply eslint rules
  client/app/vrack/add/vrack-add.controller.js
  client/app/vrack/add/vrack-add.controller.spec.js
  client/app/vrack/add/vrack-add.js
  client/app/vrack/modals/selectVrack.controller.js
  client/app/vrack/move-dialog/vrack-move-dialog.controller.js
  client/app/vrack/vrack.controller.js
  client/app/vrack/vrack.controller.spec.js
  client/app/vrack/vrack.js
  client/app/vrack/vrack.service.js
Labels: bug

#1026 fix(cloud.project.add): apply eslint rules
  client/app/cloud/project/add/cloud-project-add.config.js
  client/app/cloud/project/add/cloud-project-add.controller.js
  client/app/cloud/project/add/cloud-project-add.js
Labels: bug

#1025 fix(cloud.offer): apply eslint rules
  client/app/cloud/offer/cloud-offer.controller.js
  client/app/cloud/offer/cloud-offer.js
Labels: bug

#1027 fix(cloud.project.billing): apply eslint rules
  client/app/cloud/project/billing/cloud-project-billing.controller.js
  client/app/cloud/project/billing/cloud-project-billing.js
  client/app/cloud/project/billing/cloud-project-billing.service.js
  client/app/cloud/project/billing/consumption/cloud-project-billing-consumption.controller.js
  client/app/cloud/project/billing/consumption/cloud-project-billing-consumption.js
  client/app/cloud/project/billing/consumption/current/cloud-project-billing-consumption-current.controller.js
  client/app/cloud/project/billing/consumption/current/cloud-project-billing-consumption-current.js
  client/app/cloud/project/billing/consumption/estimate/alert/add/cloud-project-billing-consumption-estimate-alert-add.controller.js
  client/app/cloud/project/billing/consumption/estimate/cloud-project-billing-consumption-estimate.controller.js
  client/app/cloud/project/billing/consumption/estimate/cloud-project-billing-consumption-estimate.js
  client/app/cloud/project/billing/history/cloud-project-billing-history.controller.js
  client/app/cloud/project/billing/history/cloud-project-billing-history.js
  client/app/cloud/project/billing/history/details/cloud-project-billing-history-details.controller.js
  client/app/cloud/project/billing/history/details/cloud-project-billing-history-details.js
  client/app/cloud/project/billing/rights/addRights/cloud-project-billing-rights-add.controller.js
  client/app/cloud/project/billing/rights/cloud-project-billing-rights.controller.js
  client/app/cloud/project/billing/rights/cloud-project-billing-rights.js
  client/app/cloud/project/billing/vouchers/addCredit/cloud-project-billing-vouchers-add-credit-agora.controller.js
  client/app/cloud/project/billing/vouchers/addCredit/cloud-project-billing-vouchers-add-credit.controller.js
  client/app/cloud/project/billing/vouchers/addVoucher/cloud-project-billing-vouchers-add.controller.js
  client/app/cloud/project/billing/vouchers/cloud-project-billing-vouchers.controller.js
  client/app/cloud/project/billing/vouchers/cloud-project-billing-vouchers.js
  client/app/cloud/project/billing/vouchers/cloud-project-billing-vouchers.service.js
Labels: bug

#1028 fix(cloud.project.details): apply eslint rules
  client/app/cloud/project/details/cloud-project-details.controller.js
  client/app/cloud/project/details/cloud-project-details.js
Labels: bug

#1029 fix(cloud.project.openstack): apply eslint rules
  client/app/cloud/project/openstack/openstack.controller.js
  client/app/cloud/project/openstack/openstack.js
  client/app/cloud/project/openstack/users/add/openstack-users-add.controller.js
  client/app/cloud/project/openstack/users/delete/openstack-users-delete.controller.js
  client/app/cloud/project/openstack/users/openrc/openstack-users-openrc.controller.js
  client/app/cloud/project/openstack/users/openrc/openstack-users-openrc.js
  client/app/cloud/project/openstack/users/openstack-users.controller.js
  client/app/cloud/project/openstack/users/openstack-users.js
  client/app/cloud/project/openstack/users/password/openstack-users-password.service.js
  client/app/cloud/project/openstack/users/rclone/openstack-users-rclone.modal.controller.js
  client/app/cloud/project/openstack/users/rclone/openstack-users-rclone.service.js
  client/app/cloud/project/openstack/users/token/openstack-users-token.controller.js
  client/app/cloud/project/openstack/users/token/openstack-users-token.service.js
Labels: bug

#1030 fix(cloud.project.delete): apply eslint rules
  client/app/cloud/project/delete/cloud-project-delete.controller.js
Labels: bug

#1031 fix(cloud.project.rename): apply eslint rules
  client/app/cloud/project/rename/cloud-project-rename.controller.js
  client/app/cloud/project/rename/cloud-project-rename.directive.js
Labels: bug

#1032 fix(cloud.project.storage): apply eslint rules
  .eslintignore
  .eslintrc
  client/app/cloud/project/storage/services/container-tasks-runner.service.js
  client/app/cloud/project/storage/services/container.service.js
  client/app/cloud/project/storage/services/containers.service.js
  client/app/cloud/project/storage/services/containersConfiguration.service.js
  client/app/cloud/project/storage/storage-add-object/storage-add-object-controller.js
  client/app/cloud/project/storage/storage-add/storage-add.controller.js
  client/app/cloud/project/storage/storage-add/storage/add-storage-controller.js
  client/app/cloud/project/storage/storage-add/storage/step_container_type/add-storage-step-container-type-controller.js
  client/app/cloud/project/storage/storage-add/storage/step_region/add-storage-step-region-controller.js
  client/app/cloud/project/storage/storage-delete-container/storage-delete-container-controller.js
  client/app/cloud/project/storage/storage-delete-object/storage-delete-object-controller.js
  client/app/cloud/project/storage/storage-hosting-help/storage-add-object-controller.js
  client/app/cloud/project/storage/storage.controller.js
  client/app/cloud/project/storage/storage.js
Labels: bug

#1033 docs(readme): update readme file
  README.md
  cloudBanner.png
Labels: enhancement

#1034 build(babel): upgrade to the latest versions #31
  .babelrc
  package.json
  yarn.lock
Labels: enhancement

#1035 fix(home): remove maintenance operation banner from code
  client/app/home/home.controller.js
  client/app/home/home.html
Labels: bug
