Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2018-11, with the labels that each got.

#1161 refactor: update according to the new cache-loader directory
  .gitignore
  package.json
  yarn.lock
Labels: enhancement

#1162 fix(deps): update manager-webpack-config to v2.4.6
  package.json
  yarn.lock
Labels: bug

#1163 feat(iplb.farm.probe): add force SSL option for HTTP probe
  client/app/iplb/serverFarm/iplb-server-farm-edit.controller.js
  client/app/iplb/serverFarm/preview/iplb-server-farm-preview.html
  client/app/iplb/serverFarm/probe/iplb-server-farm-probe.html
  client/app/iplb/serverFarm/translations/Messages_fr_FR.xml
Labels: feature, quality check done, translation required

#1160 feat(navbar): add tracking for assistance and notifications
  client/components/navbar/navbar-notification.service.js
  client/components/navbar/navbar.service.js
Labels: enhancement, quality check done

#1165 style(navbar): animate notification icon
  client/app/common/less/navbar.less
  client/components/navbar/navbar-notification.service.js
Labels: enhancement, quality check done

#1167 fix(deps): upgrade ovh-ui-kit to v2.22.0
  package.json
  yarn.lock
Labels: bug

#1169 fix(deps): upgrade ovh-angular-otrs to v6.3.0
  package.json
  yarn.lock
Labels: bug

#1173 fix(load-balancer): ssl certificate load
  client/app/iplb/frontends/iplb-frontends-edit.controller.js
Labels: bug, quality check done

#1174 Feat/delete instance
  client/app/cloud/project/compute/infrastructure/virtualMachine/delete/cloud-project-compute-infrastructure-virtual-machine-delete.controller.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/delete/cloud-project-compute-infrastructure-virtual-machine-delete.html
  client/app/cloud/project/compute/infrastructure/virtualMachine/delete/translations/Messages_fr_FR.xml
Labels: enhancement, feature, quality check done, translation required

#1176 fix(deps): update manager-webpack-config to v2.4.7
  package.json
  yarn.lock
Labels: bug

#1179 fix(deps): upgrade manager-webpack-config to v3.0.0
  package.json
  yarn.lock
Labels: bug

#1180 Fix/instances gpu
  client/app/kubernetes/kubernetes.constants.js
Labels: bug, quality check done

#1178 feat(kube): reset cluster
  client/app/kubernetes/kubernetes.constants.js
  client/app/kubernetes/kubernetes.service.js
  client/app/kubernetes/service/kubernetes-service.controller.js
  client/app/kubernetes/service/kubernetes-service.html
  client/app/kubernetes/service/kubernetes-service.routes.js
  client/app/kubernetes/service/reset/kubernetes-service-reset.controller.js
  client/app/kubernetes/service/reset/kubernetes-service-reset.html
  client/app/kubernetes/service/reset/kubernetes-service-reset.modal.controller.js
  client/app/kubernetes/translations/Messages_en_GB.xml
  client/app/kubernetes/translations/Messages_fr_FR.xml
  yarn.lock
Labels: feature, quality check done, translation required

#1196 fix(deps): add missing ovh-angular-apiv7
  client/app/app.js
  client/app/index.js
  package.json
  yarn.lock
Labels: bug

#1177 feat(openstack): openRC v3 file download
  client/app/cloud/project/openstack/users/openrc/openstack-users-openrc.constant.js
  client/app/cloud/project/openstack/users/openrc/openstack-users-openrc.controller.js
  client/app/cloud/project/openstack/users/openrc/openstack-users-openrc.html
  client/app/cloud/project/openstack/users/openrc/translations/Messages_fr_FR.xml
Labels: enhancement, quality check done, translation required

#1195 fix(veeam.order): ask for retranslating text with issue
  client/app/vps/backup-storage/order/vps-order-backup-storage.html
  client/app/vps/translations/Messages_fr_FR.xml
Labels: bug, quality check done, translation required

#1216 fix(deps): ugrade ovh-angular-sidebar-menu to v7.2.2
  package.json
  yarn.lock
Labels: bug
