Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2018-04, with the labels that each got.

#644 chore(gruntfile): remove open task
  Gruntfile.js
  package-lock.json
  package.json
  server/app.js
Labels: enhancement

#651 Add search and filters to infrastructure list (local data)
  client/app/cloud/project/compute/infrastructure/list/cloud-project-compute-infrastructure-list.controller.js
  client/app/cloud/project/compute/infrastructure/list/cloud-project-compute-infrastructure-list.html
  client/app/cloud/project/compute/infrastructure/translations/Messages_fr_FR.xml
  client/components/cloud/project/compute/infrastructure/vrack/virtualMachine/virtualMachine.factory.js
  client/components/cloud/region/region.service.js
Labels: QC_OK

#649 Feature/logs password route
  client/app/dbaas/logs/detail/account/logs-account.service.js
  client/app/dbaas/logs/detail/account/password/logs-account-password.controller.js
  client/app/dbaas/logs/detail/account/password/logs-account-password.html
  client/app/dbaas/logs/detail/account/setup/logs-account-setup.controller.js
  client/app/dbaas/logs/detail/account/setup/logs-account-setup.html
  client/app/dbaas/logs/detail/home/logs-home-constant.js
  client/app/dbaas/logs/detail/home/logs-home-service.js
  client/app/dbaas/logs/detail/home/logs-home.controller.js
  client/app/dbaas/logs/detail/logs-detail.js
  client/app/dbaas/logs/detail/logs-detail.service.js
  client/app/dbaas/logs/detail/logs-helper.service.js
  client/app/dbaas/logs/detail/logs.constants.js
  client/app/dbaas/logs/detail/offer/logs-offer.controller.js
  client/app/dbaas/logs/detail/options/home/logs-options-home.controller.js
  client/app/dbaas/logs/header/logs-dashboard-header.controller.js
  client/app/dbaas/logs/header/logs-dashboard-header.html
Labels: enhancement

#657 fix(pci): revert infrastructure list
  client/app/cloud/project/compute/infrastructure/list/cloud-project-compute-infrastructure-list.controller.js
  client/app/cloud/project/compute/infrastructure/list/cloud-project-compute-infrastructure-list.html
Labels: bug

#674 fix(veeam): fix veeam polling stop condition
  client/app/veeam/storage/veeam-storage.html
  client/app/veeam/veeam.service.js
Labels: bug

#668 fix(pci): update vm status in the view when the model changes
  client/app/cloud/project/compute/infrastructure/list/cloud-project-compute-infrastructure-list.controller.js
  client/app/cloud/project/compute/infrastructure/list/cloud-project-compute-infrastructure-list.html
  client/components/cloud/project/compute/infrastructure/infrastructure-orchestrator.service.js
  client/components/cloud/project/compute/infrastructure/vrack/virtualMachine/virtualMachine.factory.js
Labels: QC

#673 fix: fix for new offers
  client/app/dbaas/logs/detail/logs-order.service.js
  client/app/dbaas/logs/detail/offer/logs-offer.html
  client/app/dbaas/logs/detail/offer/logs-offer.less
  client/app/dbaas/logs/translations/Messages_en_GB.xml
  client/app/dbaas/logs/translations/Messages_fr_FR.xml
Labels: Translation required

#677 fix: fix for coldstorage price
  client/app/dbaas/logs/detail/logs-order.service.js
  client/app/dbaas/logs/detail/streams/add/logs-streams-add.controller.js
  client/app/dbaas/logs/detail/streams/add/logs-streams-add.html
  client/app/dbaas/logs/detail/streams/logs-streams.service.js
  client/app/dbaas/logs/logs-constants.js
  client/app/dbaas/logs/translations/Messages_en_GB.xml
  client/app/dbaas/logs/translations/Messages_fr_FR.xml
Labels: Translation required

#681 feat(oui-stepper): add oui-stepper component default translations
  client/app/app.js
  client/app/common/translations/Messages_fr_FR.xml
Labels: Translation required

#687 chore(*): add missing stepper default translation
  client/app/app.js
  client/app/common/translations/Messages_fr_FR.xml
Labels: Translation required

#686 fix(pci): fix credit for cloud
  client/app/cloud/project/billing/vouchers/addCredit/cloud-project-billing-vouchers-add-credit.controller.js
  client/app/cloud/project/billing/vouchers/addCredit/cloud-project-billing-vouchers-add-credit.html
  client/app/cloud/project/billing/vouchers/cloud-project-billing-vouchers.controller.js
  client/app/cloud/project/billing/vouchers/cloud-project-billing-vouchers.html
  client/app/cloud/project/billing/vouchers/cloud-project-billing-vouchers.service.js
  client/app/helper/service-helper.service.js
Labels: QC_OK, bug
