Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2018-07, with the labels that each got.

#818 Fix/us quota view
  client/app/cloud/project/compute/quota/cloud-project-compute-quota.controller.js
  client/app/cloud/project/compute/quota/cloud-project-compute-quota.html
  package.json
  yarn.lock
Labels: bug, quality check required

#814 fix(pci): fix vrack loading in infrastructure view
  client/components/sidebar/sections/vrack-section.service.js
Labels: bug, quality check done

#823 fix(pci): fix auto selected flavor on vm add in diagram view
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/cloud-project-compute-infrastructure-virtualMachine-addEdit.controller.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/cloud-project-compute-infrastructure-virtualMachine-addEdit.html
Labels: bug, quality check required

#817 fix(pci): fix flags display and translations for US region
  client/app/cloud/translations/Messages_fr_FR.xml
  client/components/cloud/region/region.service.js
Labels: bug, quality check required

#802 fix: fix for table in veeam
  client/app/veeam/storage/veeam-storage.html
Labels: enhancement, quality check done

#789 Replace cui-modal with oui-modal in cloud module
  client/app/cloud/project/billing/rights/addRights/cloud-project-billing-rights-add.controller.js
  client/app/cloud/project/billing/rights/addRights/cloud-project-billing-rights-add.html
  client/app/cloud/project/billing/rights/cloud-project-billing-rights.controller.js
  client/app/cloud/project/billing/vouchers/addCredit/cloud-project-billing-vouchers-add-credit.html
  client/app/cloud/project/billing/vouchers/addVoucher/cloud-project-billing-vouchers-add.controller.js
  client/app/cloud/project/billing/vouchers/addVoucher/cloud-project-billing-vouchers-add.html
  client/app/cloud/project/openstack/users/add/openstack-users-add.controller.js
  client/app/cloud/project/openstack/users/add/openstack-users-add.html
Labels: enhancement, quality check done

#777 replaced cui-button with oui-button
  client/app/iplb/server/status/iplb-server-status-detail.html
  client/app/iplb/serverFarm/probe/iplb-server-farm-probe.html
  client/app/iplb/sslCertificate/update/iplb-ssl-certificate-update.html
  client/app/iplb/vrack/iplb-vrack.html
  client/app/ui-components/button/button.component.js
Labels: enhancement, quality check done

#833 fix(otrs): fix otrs component version
  package.json
  yarn.lock
Labels: bug

#832 feat(vps.dashboard): display warning message about upgrade
  client/app/vps/dashboard/vps-dashboard.controller.js
  client/app/vps/dashboard/vps-dashboard.html
  client/app/vps/translations/Messages_cs_CZ.xml
  client/app/vps/translations/Messages_de_DE.xml
  client/app/vps/translations/Messages_en_ASIA.xml
  client/app/vps/translations/Messages_en_AU.xml
  client/app/vps/translations/Messages_en_CA.xml
  client/app/vps/translations/Messages_en_GB.xml
  client/app/vps/translations/Messages_en_SG.xml
  client/app/vps/translations/Messages_en_US.xml
  client/app/vps/translations/Messages_es_ES.xml
  client/app/vps/translations/Messages_es_US.xml
  client/app/vps/translations/Messages_fi_FI.xml
  client/app/vps/translations/Messages_fr_CA.xml
  client/app/vps/translations/Messages_fr_FR.xml
  client/app/vps/translations/Messages_it_IT.xml
  client/app/vps/translations/Messages_lt_LT.xml
  client/app/vps/translations/Messages_nl_NL.xml
  client/app/vps/translations/Messages_pl_PL.xml
  client/app/vps/translations/Messages_pt_PT.xml
Labels: feature, quality check required

#822 Replace cui-tile with oui-tile in Logs Data Platform Options Page (Cloud Manager)
  client/app/dbaas/logs/detail/options/home/logs-options-home.html
Labels: enhancement, quality check done

#837 Revert "Merge pull request #832 from ovh-ux/hotfix/vpsUpgradeBanner"
  client/app/vps/dashboard/vps-dashboard.controller.js
  client/app/vps/dashboard/vps-dashboard.html
  client/app/vps/translations/Messages_cs_CZ.xml
  client/app/vps/translations/Messages_de_DE.xml
  client/app/vps/translations/Messages_en_ASIA.xml
  client/app/vps/translations/Messages_en_AU.xml
  client/app/vps/translations/Messages_en_CA.xml
  client/app/vps/translations/Messages_en_GB.xml
  client/app/vps/translations/Messages_en_SG.xml
  client/app/vps/translations/Messages_en_US.xml
  client/app/vps/translations/Messages_es_ES.xml
  client/app/vps/translations/Messages_es_US.xml
  client/app/vps/translations/Messages_fi_FI.xml
  client/app/vps/translations/Messages_fr_CA.xml
  client/app/vps/translations/Messages_fr_FR.xml
  client/app/vps/translations/Messages_it_IT.xml
  client/app/vps/translations/Messages_lt_LT.xml
  client/app/vps/translations/Messages_nl_NL.xml
  client/app/vps/translations/Messages_pl_PL.xml
  client/app/vps/translations/Messages_pt_PT.xml
Labels: enhancement

#808 fix(action-menu): update following changes to dropdown in ui-angular
  client/app/ui-components/tile/tile.component.js
  package.json
  yarn.lock
Labels: bug, quality check done

#801 Fix/migrate modal iplb
  client/app/iplb/frontends/delete/iplb-frontends-delete.controller.js
  client/app/iplb/frontends/delete/iplb-frontends-delete.html
  client/app/iplb/frontends/preview/iplb-frontends-preview.html
  client/app/iplb/home/iplb-home.controller.js
  client/app/iplb/home/updateQuota/iplb-update-quota.controller.js
  client/app/iplb/home/updateQuota/iplb-update-quota.html
  client/app/iplb/iplb-action.service.js
  client/app/iplb/modal/cipher/iplb-cipher-change.html
  client/app/iplb/modal/nat-ip/iplb-nat-ip-detail.html
  client/app/iplb/modal/offer/iplb-offer-change.controller.js
  client/app/iplb/modal/offer/iplb-offer-change.html
  client/app/iplb/server/delete/iplb-server-delete.controller.js
  client/app/iplb/server/delete/iplb-server-delete.html
  client/app/iplb/server/preview/iplb-server-preview.html
  client/app/iplb/server/status/iplb-server-status-detail.html
  client/app/iplb/serverFarm/delete/iplb-server-farm-delete.controller.js
  client/app/iplb/serverFarm/delete/iplb-server-farm-delete.html
  client/app/iplb/serverFarm/preview/iplb-server-farm-preview.html
  client/app/iplb/serverFarm/probe/iplb-server-farm-probe.controller.js
  client/app/iplb/serverFarm/probe/iplb-server-farm-probe.html
  client/app/iplb/sslCertificate/delete/iplb-ssl-certificate-delete.controller.js
  client/app/iplb/sslCertificate/delete/iplb-ssl-certificate-delete.html
  client/app/iplb/sslCertificate/preview/iplb-ssl-certificate-preview.html
  client/app/iplb/sslCertificate/update/iplb-ssl-certificate-update.controller.js
  client/app/iplb/sslCertificate/update/iplb-ssl-certificate-update.html
  client/app/iplb/task/preview/iplb-task-preview.html
Labels: enhancement, quality check done

#812 fix(iplb): remove unused call to /ipLoadbalancing/availableZones
  client/app/iplb/iplb-zone.service.js
Labels: enhancement, quality check required

#790 fix: fix for modals in dbaas metrics and deskaas
  client/app/dbaas/dbaas-metrics/token/delete/metrics-token-delete.html
  client/app/dbaas/dbaas-metrics/token/edit/metrics-token-edit.controller.js
  client/app/dbaas/dbaas-metrics/token/edit/metrics-token-edit.html
  client/app/dbaas/dbaas-metrics/token/preview/metrics-token-preview.html
  client/app/deskaas/deskaas-change-password/deskaas-change-password.html
  client/app/deskaas/deskaas-confirm-terminate/deskaas-confirm-terminate.html
  client/app/deskaas/deskaas-get-console-access/deskaas-get-console-access.html
Labels: enhancement, quality check done

#820 Replace cui-tile with oui-tile in Cloud Manager Home
  client/app/home/home.html
Labels: enhancement, quality check done

#826 Fix/tile iplb home
  client/app/iplb/home/iplb-home.controller.js
  client/app/iplb/home/iplb-home.html
  client/app/iplb/home/iplb-home.js
  package.json
Labels: enhancement, quality check done

#831 refactor(oui-tile): replace cui-tile with oui-tile in veeam
  client/app/veeam/dashboard/veeam-dashboard.controller.js
  client/app/veeam/dashboard/veeam-dashboard.html
  client/app/veeam/veeam.js
Labels: enhancement, quality check done

#844 Replace cui-dropdown-menu with oui-dropdown
  client/app/app.js
  client/app/dbaas/dbaas-metrics/token/metrics-token.controller.js
  client/app/iplb/configuration/iplb-configuration.controller.js
  client/app/iplb/sslCertificate/iplb-ssl-certificate.controller.js
  client/app/oui-less-override.less
  client/app/ui-components/accordion/accordion.component.js
Labels: enhancement, quality check done

#845 fix(vps): added banner about VPS upgrade until wednesday
  client/app/vps/dashboard/vps-dashboard.controller.js
  client/app/vps/dashboard/vps-dashboard.html
  client/app/vps/translations/Messages_cs_CZ.xml
  client/app/vps/translations/Messages_de_DE.xml
  client/app/vps/translations/Messages_en_ASIA.xml
  client/app/vps/translations/Messages_en_AU.xml
  client/app/vps/translations/Messages_en_CA.xml
  client/app/vps/translations/Messages_en_GB.xml
  client/app/vps/translations/Messages_en_SG.xml
  client/app/vps/translations/Messages_en_US.xml
  client/app/vps/translations/Messages_es_ES.xml
  client/app/vps/translations/Messages_es_US.xml
  client/app/vps/translations/Messages_fi_FI.xml
  client/app/vps/translations/Messages_fr_CA.xml
  client/app/vps/translations/Messages_fr_FR.xml
  client/app/vps/translations/Messages_it_IT.xml
  client/app/vps/translations/Messages_lt_LT.xml
  client/app/vps/translations/Messages_nl_NL.xml
  client/app/vps/translations/Messages_pl_PL.xml
  client/app/vps/translations/Messages_pt_PT.xml
Labels: enhancement, quality check done

#850 chore(i18n): add missing qtlids
  client/app/vps/translations/Messages_fr_FR.xml
Labels: bug

#854 chore(i18n): retrieve translations
  client/app/cloud/project/billing/consumption/estimate/alert/add/translations/Messages_en_ASIA.xml
  client/app/cloud/project/billing/consumption/estimate/alert/add/translations/Messages_en_AU.xml
  client/app/cloud/project/billing/consumption/estimate/alert/add/translations/Messages_en_CA.xml
  client/app/cloud/project/billing/consumption/estimate/alert/add/translations/Messages_en_GB.xml
  client/app/cloud/project/billing/consumption/estimate/alert/add/translations/Messages_en_SG.xml
  client/app/cloud/project/billing/consumption/estimate/alert/add/translations/Messages_en_US.xml
  client/app/cloud/project/billing/consumption/estimate/alert/add/translations/Messages_fr_CA.xml
  client/app/cloud/project/billing/consumption/estimate/alert/add/translations/Messages_it_IT.xml
  client/app/cloud/project/compute/loadbalancer/translations/Messages_es_US.xml
  client/app/vps/translations/Messages_cs_CZ.xml
  client/app/vps/translations/Messages_de_DE.xml
  client/app/vps/translations/Messages_en_ASIA.xml
  client/app/vps/translations/Messages_en_AU.xml
  client/app/vps/translations/Messages_en_CA.xml
  client/app/vps/translations/Messages_en_GB.xml
  client/app/vps/translations/Messages_en_SG.xml
  client/app/vps/translations/Messages_en_US.xml
  client/app/vps/translations/Messages_es_ES.xml
  client/app/vps/translations/Messages_es_US.xml
  client/app/vps/translations/Messages_fi_FI.xml
  client/app/vps/translations/Messages_fr_CA.xml
  client/app/vps/translations/Messages_it_IT.xml
  client/app/vps/translations/Messages_lt_LT.xml
  client/app/vps/translations/Messages_nl_NL.xml
  client/app/vps/translations/Messages_pl_PL.xml
  client/app/vps/translations/Messages_pt_PT.xml
Labels: bug

#852 fix(ssh): fix ssh create US guide url
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.controller.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/cloud-project-compute-infrastructure-virtualMachine-addEdit.controller.js
  client/app/config/US/common.constants.js
Labels: bug, quality check done

#803 feat(navbar): apply translations for navbar placeholder
  client/app/app.js
  client/app/common/translations/Messages_fr_FR.xml
  client/components/navbar/navbar-notification.service.js
Labels: feature, quality check done

#855 chore(vps): remove vps upgrade banner
  client/app/vps/dashboard/vps-dashboard.controller.js
  client/app/vps/dashboard/vps-dashboard.html
  client/app/vps/translations/Messages_cs_CZ.xml
  client/app/vps/translations/Messages_de_DE.xml
  client/app/vps/translations/Messages_en_ASIA.xml
  client/app/vps/translations/Messages_en_AU.xml
  client/app/vps/translations/Messages_en_CA.xml
  client/app/vps/translations/Messages_en_GB.xml
  client/app/vps/translations/Messages_en_SG.xml
  client/app/vps/translations/Messages_en_US.xml
  client/app/vps/translations/Messages_es_ES.xml
  client/app/vps/translations/Messages_es_US.xml
  client/app/vps/translations/Messages_fi_FI.xml
  client/app/vps/translations/Messages_fr_CA.xml
  client/app/vps/translations/Messages_fr_FR.xml
  client/app/vps/translations/Messages_it_IT.xml
  client/app/vps/translations/Messages_lt_LT.xml
  client/app/vps/translations/Messages_nl_NL.xml
  client/app/vps/translations/Messages_pl_PL.xml
  client/app/vps/translations/Messages_pt_PT.xml
Labels: enhancement

#853 feat(pci): manager terminate project for US
  client/app/cloud/project/delete/cloud-project-delete.controller.js
Labels: enhancement, quality check done

#836 Fix/us open stack horizon url
  client/app/config/US/common.constants.js
Labels: bug, quality check done

#840 Fix/tile metrics home
  client/app/dbaas/dbaas-metrics/dashboard/metrics-dashboard.html
  client/app/dbaas/dbaas-metrics/metrics.js
Labels: enhancement, quality check done

#863 fix(*): use heading attribut on oui-back-button
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.html
  client/app/cloud/project/compute/loadbalancer/configure/compute-loadbalancer-configure.html
  client/app/cloud/project/storage/storage-add/storage-add.html
  client/app/dbaas/dbaas-metrics/token/add/metrics-token-add.html
  client/app/dbaas/logs/detail/aliases/link/aliases-link.html
  client/app/dbaas/logs/detail/inputs/add/logs-inputs-add.html
  client/app/dbaas/logs/detail/offer/logs-offer.html
  client/app/dbaas/logs/detail/options/home/logs-options-home.html
  client/app/dbaas/logs/detail/options/manage/logs-options-manage.html
  client/app/dbaas/logs/detail/streams/add/logs-streams-add.html
  client/app/dbaas/logs/detail/streams/alerts/add/alerts-add.html
  client/app/dbaas/logs/detail/streams/alerts/home/alerts-home.html
  client/app/dbaas/logs/detail/tokens/logs-tokens.html
  client/app/deskaas/deskaas-upgrade/deskaas-upgrade.html
  client/app/iplb/frontends/iplb-frontends-edit.html
  client/app/iplb/serverFarm/iplb-server-farm-edit.html
  client/app/iplb/sslCertificate/iplb-ssl-certificate-edit.html
  client/app/iplb/sslCertificate/order/iplb-ssl-certificate-order.html
  client/app/iplb/vrack/iplb-vrack-edit.html
  client/app/iplb/zone/iplb-zone-add.html
  client/app/iplb/zone/iplb-zone-delete.html
  client/app/nasha/partition/access/nasha-partition-access.html
  client/app/vps/upgrade/vps-upgrade.html
Labels: enhancement

#862 fix(ipfo): fix ipfo US order
  client/app/cloud/project/compute/infrastructure/cloud-project-compute-infrastructure.service.js
  client/app/cloud/project/compute/infrastructure/ip/failover/buy/cloud-project-compute-infrastructure-ip-failover-buy-agora.controller.js
  client/app/cloud/project/compute/infrastructure/ip/failover/buy/cloud-project-compute-infrastructure-ip-failover-buy-agora.html
Labels: bug, quality check done

#859 fix(pci): fix support url
  client/app/cloud/project/compute/infrastructure/diagram/cloud-project-compute-infrastructure-diagram.html
  client/app/cloud/project/details/cloud-project-details.controller.js
  client/app/cloud/project/details/cloud-project-details.html
  client/app/cloud/project/details/translations/Messages_fr_FR.xml
Labels: bug, quality check required

#864 feat(cloud): add button for BigData platform CLI call
  client/app/cloud/project/compute/infrastructure/openstackClient/cloud-project-compute-infrastructure-openstack-client.controller.js
Labels: enhancement, quality check done

#865 chore(makefile): remove submodule target
  Makefile
Labels: enhancement

#843 Fix/tile vps home
  client/app/vps/dashboard/vps-dashboard.controller.js
  client/app/vps/dashboard/vps-dashboard.html
Labels: enhancement, quality check done

#795 Remove cui-wizard-form and cui-wizard-step
  client/app/ui-components/wizardForm/wizardForm.component.js
  client/app/ui-components/wizardForm/wizardForm.html
  client/app/ui-components/wizardStep/wizardStep.component.js
  client/app/ui-components/wizardStep/wizardStep.html
  client/app/ui-components/wizardStep/wizardStep.less
  client/app/vps/additional-disk/order/vps-order-additional-disk.controller.js
  client/app/vps/additional-disk/order/vps-order-additional-disk.html
  client/app/vps/backup-storage/order/vps-order-backup-storage.html
  client/app/vps/snapshot-order/vps-snapshot-order.html
  client/app/vps/translations/Messages_fr_FR.xml
  client/app/vps/upgrade/vps-upgrade.html
  client/app/vps/veeam/order/vps-order-veeam.html
  client/app/vps/vps.less
  client/app/vps/windows-order/vps-windows-order.html
Labels: enhancement, quality check done, translation required

#860 fix(sidebar): add back project management section in sidebar for EU
  client/components/sidebar/products/project-sidebar.service.js
Labels: bug

#830 fix(cloud): openstack terminal copy/paste on safari
  client/.eslintrc.json
  client/app/cloud/project/compute/infrastructure/openstackClient/cloud-project-compute-infrastructure-openstack-client.controller.js
  client/app/cloud/project/compute/infrastructure/openstackClient/cloud-project-compute-infrastructure-openstack-client.html
  client/app/cloud/project/compute/infrastructure/openstackClient/cloud-project-compute-infrastructure-openstack-client.less
  client/app/cloud/project/compute/infrastructure/openstackClient/cloud-project-compute-infrastructure-openstack-client.service.js
  client/components/hterm/hterm.directive.js
  client/components/hterm/hterm.service.js
  dependencies.json
  package.json
Labels: enhancement, quality check done

#821 Migrate cui tile to oui tile in cloud desktop dashboard
  client/app/deskaas/deskaas-details/deskaas-details.html
  client/app/deskaas/deskaas-details/deskaas-details.js
  client/app/oui-less-override.less
Labels: quality check done

#796 Migrate cui modal vps
  client/app/veeam/storage/update-quota/veeam-storage-update-quota.controller.js
  client/app/veeam/storage/update-quota/veeam-storage-update-quota.html
  client/app/vps/modal/backup-storage/add-backup-storage.controller.js
  client/app/vps/modal/backup-storage/add-backup-storage.html
  client/app/vps/modal/backup-storage/delete-backup-storage.controller.js
  client/app/vps/modal/backup-storage/delete-backup-storage.html
  client/app/vps/modal/backup-storage/edit-backup-storage.controller.js
  client/app/vps/modal/backup-storage/edit-backup-storage.html
  client/app/vps/modal/backup-storage/password-backup-storage.controller.js
  client/app/vps/modal/backup-storage/password-backup-storage.html
  client/app/vps/modal/option/vps-option-terminate.controller.js
  client/app/vps/modal/option/vps-option-terminate.html
  client/app/vps/modal/secondary-dns/add-secondary-dns.controller.js
  client/app/vps/modal/secondary-dns/add-secondary-dns.html
  client/app/vps/modal/secondary-dns/delete-secondary-dns.controller.js
  client/app/vps/modal/secondary-dns/delete-secondary-dns.html
  client/app/vps/modal/shortcut/display-ips/vps-display-ips.controller.js
  client/app/vps/modal/shortcut/display-ips/vps-display-ips.html
  client/app/vps/modal/shortcut/kvm/vps-kvm.controller.js
  client/app/vps/modal/shortcut/kvm/vps-kvm.html
  client/app/vps/modal/shortcut/kvm/vps-kvm.less
  client/app/vps/modal/shortcut/monitoring-sla/vps-monitoring-sla.controller.js
  client/app/vps/modal/shortcut/monitoring-sla/vps-monitoring-sla.html
  client/app/vps/modal/shortcut/password/vps-password.controller.js
  client/app/vps/modal/shortcut/password/vps-password.html
  client/app/vps/modal/shortcut/reboot/vps-reboot.controller.js
  client/app/vps/modal/shortcut/reboot/vps-reboot.html
  client/app/vps/modal/shortcut/reinstall/vps-reinstall.html
  client/app/vps/modal/shortcut/reinstall/vps-reinstall.less
  client/app/vps/modal/shortcut/reverse-dns/vps-reverse-dns.html
  client/app/vps/modal/snapshot/snapshot-delete.controller.js
  client/app/vps/modal/snapshot/snapshot-delete.html
  client/app/vps/modal/snapshot/snapshot-restore.controller.js
  client/app/vps/modal/snapshot/snapshot-restore.html
  client/app/vps/modal/snapshot/snapshot-take.controller.js
  client/app/vps/modal/snapshot/snapshot-take.html
  client/app/vps/modal/veeam/mount/vps-mount.html
  client/app/vps/modal/veeam/restore/vps-restore.html
Labels: quality check done

#868 fix(sidebar): add back storage and openstack items
  client/components/sidebar/products/project-sidebar.service.js
Labels: bug
