Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2018-06, with the labels that each got.

#779 fix(vrack add): display order url for us customers
  client/app/vrack/add/vrack-add.controller.js
  client/app/vrack/add/vrack-add.html
Labels: bug

#784 fix(vrack add): change copy for us customers
  client/app/vrack/add/translations/Messages_en_US.xml
  client/app/vrack/add/translations/Messages_fr_FR.xml
  client/app/vrack/add/vrack-add.html
Labels: bug

#774 fix(order): set direct ip order url for US
  client/app/config/US/common.constants.js
  client/components/sidebar/products/ip-sidebar.service.js
  client/components/sidebar/sidebar-order.service.js
Labels: enhancement, quality check done

#780 feat(track): udpate tracking to handle sidebar button order
  client/components/sidebar/products/cda-sidebar.service.js
  client/components/sidebar/products/cloud-db-sidebar.service.js
  client/components/sidebar/products/cloud-desktop-sidebar.service.js
  client/components/sidebar/products/dbaasts-sidebar.service.js
  client/components/sidebar/products/dedicated-cloud-sidebar.service.js
  client/components/sidebar/products/dedicated-server-sidebar.service.js
  client/components/sidebar/products/ip-sidebar.service.js
  client/components/sidebar/products/iplb-sidebar.service.js
  client/components/sidebar/products/license-sidebar.service.js
  client/components/sidebar/products/logs-sidebar.service.js
  client/components/sidebar/products/nasha-sidebar.service.js
  client/components/sidebar/products/project-sidebar.service.js
  client/components/sidebar/products/veeam-sidebar.service.js
  client/components/sidebar/products/vps-sidebar.service.js
  client/components/sidebar/products/vrack-sidebar.service.js
  client/components/sidebar/sidebar-order.service.js
  package.json
Labels: quality check done

#788 fix(openstack): fix token too long display issues
  client/app/cloud/project/openstack/users/token/openstack-users-token.html
Labels: bug, quality check done

#791 fix(vps:upgrade): Allow to upgrade new models
  client/app/vps/upgrade/vps-upgrade.controller.js
  client/app/vps/upgrade/vps-upgrade.html
Labels: bug

#793 feat(navbar): add placeholder translation
  client/app/common/translations/Messages_fr_FR.xml
Labels: translation required

#771 fix: cui-radio-bar removal
  client/app/dbaas/logs/detail/aliases/link/aliases-link.html
  client/app/iplb/frontends/iplb-frontends-edit.html
  client/app/iplb/graph/iplb-graph.html
  client/app/iplb/serverFarm/iplb-server-farm-edit.html
  client/app/iplb/serverFarm/probe/iplb-server-farm-probe.html
  client/app/iplb/sslCertificate/order/iplb-ssl-certificate-order.html
  client/app/oui-less-override.less
  client/app/ui-components/radio-bar/radio-bar.component.js
  client/app/ui-components/radio-bar/radio-bar.less
Labels: enhancement, quality check done

#800 fix(iplb): remove unused call to /ipLoadbalancing/availableZones
  client/app/iplb/iplb-zone.service.js
Labels: enhancement, good first issue, quality check required

#805 fix(guides): update homepage guides urls for ASIA, AU and SG
  client/components/docs/docs.constants.js
  client/components/docs/docs.service.js
Labels: bug, quality check done

#804 Remove cui-status-icon
  client/app/iplb/configuration/iplb-configuration.controller.js
  client/app/iplb/home/status-card.component.js
  client/app/iplb/server/iplb-server-status.component.js
  client/app/oui-less-override.less
  client/app/ui-components/status-icon/status-icon.component.js
  client/app/ui-components/status-icon/status-icon.less
  client/app/ui-components/tile/custom/item/cui-tile-item-status.component.js
Labels: enhancement, quality check done

#815 fix(pci): set message to html format when trying to delete snapshot disk
  client/app/cloud/project/compute/infrastructure/diagram/cloud-project-compute-infrastructure-diagram.controller.js
Labels: bug, quality check done

#816 fix(pci): translations load error in diagram infra view
  client/app/cloud/project/compute/infrastructure/diagram/cloud-project-compute-infrastructure-diagram.js
Labels: bug, quality check done

#810 feat(pci project): enable order in sidebar action menu
  client/app/cloud/offer/cloud-offer.controller.js
  client/app/cloud/offer/cloud-offer.html
  client/app/config/US/common.constants.js
  client/components/featureAvailability/featureAvailability.service.js
Labels: feature, quality check required

#787 feat(*): move storage and openstack from sidebar to tabs - [do not merge yet]
  client/app/cloud/offer/cloud-offer.controller.js
  client/app/cloud/offer/cloud-offer.html
  client/app/cloud/project/billing/cloud-project-billing.html
  client/app/cloud/project/billing/quota/cloud-project-billing-quota.js
  client/app/cloud/project/billing/translations/Messages_fr_FR.xml
  client/app/cloud/project/compute/cloud-project-compute.html
  client/app/cloud/project/compute/infrastructure/diagram/cloud-project-compute-infrastructure-diagram.controller.js
  client/app/cloud/project/compute/infrastructure/diagram/cloud-project-compute-infrastructure-diagram.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.html
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/cloud-project-compute-infrastructure-virtualMachine-addEdit.html
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/translations/Messages_fr_FR.xml
  client/app/cloud/project/compute/quota/cloud-project-compute-quota.controller.js
  client/app/cloud/project/compute/quota/cloud-project-compute-quota.html
  client/app/cloud/project/compute/quota/cloud-project-compute-quota.js
  client/app/cloud/project/compute/quota/cloud-project-compute-quota.less
  client/app/cloud/project/compute/quota/translations/Messages_cs_CZ.xml
  client/app/cloud/project/compute/quota/translations/Messages_de_DE.xml
  client/app/cloud/project/compute/quota/translations/Messages_en_ASIA.xml
  client/app/cloud/project/compute/quota/translations/Messages_en_AU.xml
  client/app/cloud/project/compute/quota/translations/Messages_en_CA.xml
  client/app/cloud/project/compute/quota/translations/Messages_en_GB.xml
  client/app/cloud/project/compute/quota/translations/Messages_en_SG.xml
  client/app/cloud/project/compute/quota/translations/Messages_en_US.xml
  client/app/cloud/project/compute/quota/translations/Messages_es_ES.xml
  client/app/cloud/project/compute/quota/translations/Messages_es_US.xml
  client/app/cloud/project/compute/quota/translations/Messages_fi_FI.xml
  client/app/cloud/project/compute/quota/translations/Messages_fr_CA.xml
  client/app/cloud/project/compute/quota/translations/Messages_fr_FR.xml
  client/app/cloud/project/compute/quota/translations/Messages_it_IT.xml
  client/app/cloud/project/compute/quota/translations/Messages_lt_LT.xml
  client/app/cloud/project/compute/quota/translations/Messages_nl_NL.xml
  client/app/cloud/project/compute/quota/translations/Messages_pl_PL.xml
  client/app/cloud/project/compute/quota/translations/Messages_pt_PT.xml
  client/app/cloud/project/compute/translations/Messages_fr_FR.xml
  client/app/cloud/project/openstack/openstack.controller.js
  client/app/cloud/project/openstack/openstack.html
  client/app/cloud/project/openstack/openstack.js
  client/app/cloud/project/openstack/users/openrc/openstack-users-openrc.js
  client/app/cloud/project/openstack/users/openstack-users.js
  client/app/cloud/project/storage/storage-add/storage-add.html
  client/app/cloud/project/storage/storage-add/storage/add-storage-controller.js
  client/app/cloud/project/storage/storage-containers/table.html
  client/app/cloud/project/storage/storage-details/storage-details.controller.js
  client/app/cloud/project/storage/storage-details/storage-details.html
  client/app/cloud/project/storage/storage-header.html
  client/app/cloud/project/storage/storage.controller.js
  client/app/cloud/project/storage/storage.html
  client/app/cloud/project/storage/storage.js
  client/app/config/US/common.constants.js
  client/components/featureAvailability/featureAvailability.service.js
  client/components/navbar/navbar.service.js
  client/components/sidebar/products/project-sidebar.service.js
  yarn.lock
Labels: feature, quality check done

#786 feat(quota): move quota tab - [do not merge yet]
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/cloud-project-compute-infrastructure-virtualMachine-addEdit.html
  client/app/cloud/project/compute/quota/cloud-project-compute-quota.html
Labels: feature, quality check done
