Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2018-10, with the labels that each got.

#1042 build(webpack): add missing extras entry
  webpack.config.js
Labels: bug

#1043 build(webpack): add hash to output.filename
  webpack.config.js
Labels: enhancement

#1048 docs(contributing): referring to the correct eslint config url
  CONTRIBUTING.md
Labels: bug

#1050 fix(navbar): add common translations to avoid clipping
  client/components/navbar/navbar.service.js
Labels: bug

#1052 build(package): add version postversion hook
  package.json
Labels: bug

#1058 build(scripts.test): run yarn lint command
  package.json
Labels: bug

#1056 Feat/summit banner
  client/app/app.less
  client/app/home/announcement/announcement-summit.config.js
  client/app/home/announcement/announcement-summit.controller.js
  client/app/home/announcement/announcement-summit.html
  client/app/home/announcement/announcement.less
  client/app/home/announcement/translations/Messages_cs_CZ.xml
  client/app/home/announcement/translations/Messages_de_DE.xml
  client/app/home/announcement/translations/Messages_en_ASIA.xml
  client/app/home/announcement/translations/Messages_en_AU.xml
  client/app/home/announcement/translations/Messages_en_CA.xml
  client/app/home/announcement/translations/Messages_en_GB.xml
  client/app/home/announcement/translations/Messages_en_SG.xml
  client/app/home/announcement/translations/Messages_en_US.xml
  client/app/home/announcement/translations/Messages_es_ES.xml
  client/app/home/announcement/translations/Messages_es_US.xml
  client/app/home/announcement/translations/Messages_fi_FI.xml
  client/app/home/announcement/translations/Messages_fr_CA.xml
  client/app/home/announcement/translations/Messages_fr_FR.xml
  client/app/home/announcement/translations/Messages_it_IT.xml
  client/app/home/announcement/translations/Messages_lt_LT.xml
  client/app/home/announcement/translations/Messages_nl_NL.xml
  client/app/home/announcement/translations/Messages_pl_PL.xml
  client/app/home/announcement/translations/Messages_pt_PT.xml
  client/app/home/home.controller.js
  client/app/home/home.html
  client/app/home/home.js
  client/app/home/translations/Messages_fr_FR.xml
  client/assets/images/announcement/summit/summit_2017_en.png
  client/assets/images/announcement/summit/summit_2017_fr.png
  client/assets/images/summit/banner-manager-2500x235-en.jpg
  client/assets/images/summit/banner-manager-2500x235-fr.jpg
  client/assets/images/summit/banner-manager-768x200-en.jpg
  client/assets/images/summit/banner-manager-768x200-fr.jpg
Labels: feature, quality check

#1059 fix(instance modale): remove strong balise for reboot
  client/app/ui-components/modal/confirmation-modal/confirmation-modal.html
Labels: bug, quality check

#1057 [RFR] — build: remove deprecated npm-scripts-config|conventional-changelog
  .scriptsrc
  package.json
  yarn.lock
Labels: enhancement

#1066 fix: update gitignore file
  .gitignore
  yarn.lock
Labels: enhancement

#1060 fix(deskass password): fix position of pwd requirements informations
  client/app/deskaas/deskaas-change-password/deskaas-change-password.html
Labels: bug, quality check done

#1065 fix(home): display Summit banner in some subsidaries only
  client/app/home/home.controller.js
  client/app/home/home.html
Labels: bug, quality check

#1069 fix: remove border top of the summit banner
  client/app/cloud/cloud.variables.less
  client/app/cloud/project/billing/rights/cloud-project-billing-rights.less
  client/app/cloud/project/storage/storage.less
  client/app/common/less/navbar.less
  client/app/oui-less-override.less
  yarn.lock
Labels: bug

#1068 fix(translations): add back sso modal translations
  client/components/sso/ovh-angular-sso-auth-modal-plugin.js
Labels: bug

#1072 Fix/project creation
  client/app/cloud/project/cloud-project.controller.js
  client/app/cloud/project/details/cloud-project-details.controller.js
  client/components/hterm/hterm.directive.js
  client/components/sidebar/products/project-sidebar.service.js
Labels: bug, quality check done

#1074 build: add clean script
  package.json
Labels: enhancement

#1077 fix(cloud.infra): infra tab state
  client/app/cloud/project/compute/cloud-project-compute.html
Labels: bug, quality check done

#1076 build: remove duplicate dependencies
  .gitignore
  client/app/cloud/project/storage/storage-add/storage-add.less
  client/app/common/less/navbar.less
  package.json
  yarn.lock
Labels: enhancement

#1038 feat(kubernetes): add kubernetes section
  client/app/kubernetes/containers/kubernetes-containers.component.js
  client/app/kubernetes/containers/kubernetes-containers.controller.js
  client/app/kubernetes/containers/kubernetes-containers.html
  client/app/kubernetes/containers/kubernetes-containers.routes.js
  client/app/kubernetes/kubernetes.component.js
  client/app/kubernetes/kubernetes.constants.js
  client/app/kubernetes/kubernetes.controller.js
  client/app/kubernetes/kubernetes.html
  client/app/kubernetes/kubernetes.routes.js
  client/app/kubernetes/kubernetes.service.js
  client/app/kubernetes/nodes/add/kubernetes-nodes-add.controller.js
  client/app/kubernetes/nodes/add/kubernetes-nodes-add.html
  client/app/kubernetes/nodes/delete/kubernetes-nodes-delete.controller.js
  client/app/kubernetes/nodes/delete/kubernetes-nodes-delete.html
  client/app/kubernetes/nodes/kubernetes-nodes.component.js
  client/app/kubernetes/nodes/kubernetes-nodes.controller.js
  client/app/kubernetes/nodes/kubernetes-nodes.html
  client/app/kubernetes/nodes/kubernetes-nodes.routes.js
  client/app/kubernetes/service/kubernetes-service.component.js
  client/app/kubernetes/service/kubernetes-service.controller.js
  client/app/kubernetes/service/kubernetes-service.html
  client/app/kubernetes/service/kubernetes-service.routes.js
  client/app/kubernetes/translations/Messages_fr_FR.xml
  client/components/sidebar/products/kubernetes-sidebar.service.js
  client/components/sidebar/sections/paas-section.service.js
  package.json
  yarn.lock
Labels: feature, quality check done, translation required

#1085 fix(kube): remove icon from translation
  client/app/kubernetes/translations/Messages_fr_FR.xml
Labels: bug

#1084 fix(scripts.clean): add missing rimraf dependency
  package.json
Labels: bug

#1083 fix(kube): prevent adding node on vps instances
  client/app/kubernetes/kubernetes.constants.js
  client/app/kubernetes/nodes/add/kubernetes-nodes-add.controller.js
Labels: quality check done

#1090 build(changelog): use npx conventional-changelog-cli with angular preset
  package.json
  yarn.lock
Labels: enhancement

#1094 chore(clouddb): translations for clouddb
  client/app/common/translations/Messages_fr_FR.xml
  client/app/vps/translations/Messages_fr_FR.xml
Labels: translation required

#1037 feat(project.compute.infrastructure): deploy stack step-by-step
  client/app/cloud/project/cloud-project.controller.js
  client/app/cloud/project/compute/infrastructure/cloud-project-compute-infrastructure.js
  client/app/cloud/project/compute/infrastructure/diagram/cloud-project-compute-infrastructure-diagram.html
  client/app/cloud/project/compute/infrastructure/iac/deploy/cloud-project-compute-infrastructure-iac-deploy.controller.js
  client/app/cloud/project/compute/infrastructure/iac/deploy/cloud-project-compute-infrastructure-iac-deploy.html
  client/app/cloud/project/compute/infrastructure/iac/deploy/cloud-project-compute-infrastructure-iac-deploy.js
  client/app/cloud/project/compute/infrastructure/iac/deploy/translations/Messages_fr_FR.xml
  client/app/cloud/project/compute/infrastructure/iac/view/cloud-project-compute-infrastructure-iac-view.controller.js
  client/app/cloud/project/compute/infrastructure/iac/view/cloud-project-compute-infrastructure-iac-view.html
  client/app/cloud/project/compute/infrastructure/iac/view/cloud-project-compute-infrastructure-iac-view.js
  client/app/cloud/project/compute/infrastructure/iac/view/translations/Messages_fr_FR.xml
  client/app/cloud/project/compute/infrastructure/list/cloud-project-compute-infrastructure-list.html
  client/app/cloud/project/compute/infrastructure/openstackClient/cloud-project-compute-infrastructure-openstack-client.controller.js
  client/app/cloud/project/compute/infrastructure/openstackClient/cloud-project-compute-infrastructure-openstack-client.html
  client/app/cloud/project/compute/infrastructure/openstackClient/cloud-project-compute-infrastructure-openstack-client.service.js
  client/app/cloud/project/compute/infrastructure/translations/Messages_fr_FR.xml
  client/app/cloud/project/details/cloud-project-details.controller.js
  client/assets/images/cloud/apps/terraform-ovh-publiccloud-k8s.png
  client/components/hterm/hterm.directive.js
  client/components/sidebar/products/project-sidebar.service.js
  yarn.lock
Labels: feature, quality check done, translation required

#1101 build(commitlint): remove unused config-conventional
  .commitlintrc.js
  package.json
  yarn.lock
Labels: enhancement

#1105 fix(ssh-creation): button missing in windows tab
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.controller.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.html
Labels: bug, quality check done

#1108 fix(openstack): route fix
  client/app/cloud/project/openstack/openstack.controller.js
  client/app/cloud/project/openstack/openstack.js
Labels: bug, quality check done

#1086 feat(virtualmachine.add): handle new GPU offers
  client/app/cloud/cloud.constants.js
  client/app/cloud/project/compute/infrastructure/flavor.service.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.controller.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.service.js
Labels: feature, quality check done

#1087 Feat/clouddb
  client/app/config/all.eu.js
  client/app/vps/cloud-database/order/vps-cloud-database-order.controller.js
  client/app/vps/cloud-database/order/vps-cloud-database-order.html
  client/app/vps/cloud-database/vps-cloud-database.controller.js
  client/app/vps/cloud-database/vps-cloud-database.html
  client/app/vps/translations/Messages_fr_FR.xml
  client/app/vps/vps-header.controller.js
  client/app/vps/vps-header.html
  client/app/vps/vps.js
  client/components/duration/duration-filter.js
  client/components/featureAvailability/featureAvailability.service.js
  client/components/manager-preload/manager-preload.less
  client/components/price/price-filter.js
  package.json
  yarn.lock
Labels: feature, quality check done

#1102 Feature/kubernetes quota
  client/app/kubernetes/kubernetes.service.js
  client/app/kubernetes/nodes/add/kubernetes-nodes-add.controller.js
  client/app/kubernetes/nodes/add/kubernetes-nodes-add.html
  client/app/kubernetes/translations/Messages_fr_FR.xml
  client/components/navbar/navbar.service.js
  client/components/sidebar/translations/Messages_fr_FR.xml
Labels: enhancement, quality check done, translation required

#1107 feat(project.compute.infrastructure): deploy stack step-by-step
  client/app/cloud/project/compute/infrastructure/diagram/cloud-project-compute-infrastructure-diagram.html
  client/app/cloud/project/compute/infrastructure/iac/view/translations/Messages_fr_FR.xml
  client/app/cloud/project/compute/infrastructure/list/cloud-project-compute-infrastructure-list.html
  client/assets/images/cloud/apps/ovh-analytics-openstack.png
Labels: enhancement, quality check done, translation required

#1122 Feat/summit banner : change subscription banner to live banner
  client/app/home/home.html
  client/app/home/translations/Messages_cs_CZ.xml
  client/app/home/translations/Messages_de_DE.xml
  client/app/home/translations/Messages_en_ASIA.xml
  client/app/home/translations/Messages_en_AU.xml
  client/app/home/translations/Messages_en_CA.xml
  client/app/home/translations/Messages_en_GB.xml
  client/app/home/translations/Messages_en_SG.xml
  client/app/home/translations/Messages_en_US.xml
  client/app/home/translations/Messages_es_ES.xml
  client/app/home/translations/Messages_es_US.xml
  client/app/home/translations/Messages_fi_FI.xml
  client/app/home/translations/Messages_fr_CA.xml
  client/app/home/translations/Messages_fr_FR.xml
  client/app/home/translations/Messages_it_IT.xml
  client/app/home/translations/Messages_lt_LT.xml
  client/app/home/translations/Messages_nl_NL.xml
  client/app/home/translations/Messages_pl_PL.xml
  client/app/home/translations/Messages_pt_PT.xml
  client/assets/images/summit/banner-manager-2500x235-en.jpg
  client/assets/images/summit/banner-manager-2500x235-fr.jpg
  client/assets/images/summit/banner-manager-768x200-en.jpg
  client/assets/images/summit/banner-manager-768x200-fr.jpg
Labels: quality check done

#1133 fix(translations): en_asia & en_sg work now correctly
  client/components/cloud/project/billing/cloud-project-billing.js
  client/components/ovh-angular-otrs/ovh-angular-otrs.js
  client/components/ovh-task-alert/ovh-task-alert.js
  client/components/sidebar/sidebar.js
  client/components/sso/ovh-angular-sso-auth-modal-plugin.js
  yarn.lock
Labels: bug, quality check

#1132 refactor: remove summit banner
  client/app/home/home.controller.js
  client/app/home/home.html
  client/app/home/translations/Messages_cs_CZ.xml
  client/app/home/translations/Messages_de_DE.xml
  client/app/home/translations/Messages_en_ASIA.xml
  client/app/home/translations/Messages_en_AU.xml
  client/app/home/translations/Messages_en_CA.xml
  client/app/home/translations/Messages_en_GB.xml
  client/app/home/translations/Messages_en_SG.xml
  client/app/home/translations/Messages_en_US.xml
  client/app/home/translations/Messages_es_ES.xml
  client/app/home/translations/Messages_es_US.xml
  client/app/home/translations/Messages_fi_FI.xml
  client/app/home/translations/Messages_fr_CA.xml
  client/app/home/translations/Messages_fr_FR.xml
  client/app/home/translations/Messages_it_IT.xml
  client/app/home/translations/Messages_lt_LT.xml
  client/app/home/translations/Messages_nl_NL.xml
  client/app/home/translations/Messages_pl_PL.xml
  client/app/home/translations/Messages_pt_PT.xml
  client/assets/images/summit/banner-manager-2500x235-en.jpg
  client/assets/images/summit/banner-manager-2500x235-fr.jpg
  client/assets/images/summit/banner-manager-768x200-en.jpg
  client/assets/images/summit/banner-manager-768x200-fr.jpg
Labels: enhancement, quality check done

#1136 refactor(components): init cloudUniverseComponents module
  client/app/app.js
  client/cloudUniverseComponents/index.js
Labels: :jack_o_lantern: one-manager

#1140 refactor(eslint): switch to json format as configuration file
  .eslintrc.json
Labels: enhancement

#1141 refactor: extract configuration from package.json into json files
  .huskyrc.json
  .lintstagedrc.json
  package.json
Labels: enhancement

#1142 build(scripts): add clean dist script
  package.json
Labels: enhancement

#1143 build(deps): upgrade manager-webpack-config to v2.3.4
  yarn.lock
Labels: enhancement

#1144 fix: fix click on select picker on safari
  yarn.lock
Labels: bug, quality check done

#1149 feat(config): add veeam enterprise urls for subs
  client/app/config/all.ca.js
  client/app/config/all.eu.js
  client/components/featureAvailability/featureAvailability.service.js
Labels: feature, quality check done

#1123 Feat/t1 gpu infrastructure view
  client/app/cloud/project/compute/infrastructure/diagram/cloud-project-compute-infrastructure-diagram.html
  client/app/cloud/project/compute/infrastructure/translations/Messages_fr_FR.xml
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/cloud-project-compute-infrastructure-virtualMachine-addEdit.controller.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/translations/Messages_fr_FR.xml
  client/components/cloud/project/compute/infrastructure/infrastructure-orchestrator.service.js
Labels: feature, quality check done, translation required

#1151 Bump manager webpack config
  README.md
  yarn.lock
Labels: enhancement

#1150 fix(iplb.frontends): fix ips whitelist removal
  client/app/iplb/frontends/iplb-frontends-edit.controller.js
Labels: bug, quality check done

#1153 build(htmlhint): add htmlhint configuration
  .htmlhintrc
  .lintstagedrc.json
  package.json
  yarn.lock
Labels: enhancement

#1154 style(package.json): sort entries
  package.json
Labels: enhancement

#1157 refactor: use @ovh-ux/translate-async-loader
  client/app/app.js
  client/app/async-loader.factory.js
  package.json
  yarn.lock
Labels: :jack_o_lantern: one-manager

#1158 build(deps): upgrade manager-webpack-config to v2.4.0
  client/app/cloud/project/compute/infrastructure/privateNetwork/dialog/cloud-project-compute-infrastructure-privateNetwork-dialog.service.js
  client/app/cloud/project/compute/snapshot/cloud-project-compute-snapshot-price.service.js
  package.json
  yarn.lock
Labels: :jack_o_lantern: one-manager
