Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2018-08, with the labels that each got.

#874 chore(deps): bump ovh-ui-kit and ovh-ui-angular
  client/app/app.tpl.less
  package.json
  yarn.lock
Labels: enhancement, ovh-ui-kit

#797 fix: retrieves correct guide url
  client/app/cda/details/cda-details.controller.js
  client/app/cda/translations/Messages_fr_FR.xml
  client/app/config/CA/common.constants.js
  client/app/config/EU/common.constants.js
Labels: bug, quality check done, translation required

#877 fix(flavors): fix flavors in diagram view
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/cloud-project-compute-infrastructure-virtualMachine-addEdit.controller.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/cloud-project-compute-infrastructure-virtualMachine-addEdit.html
Labels: bug, quality check done

#880 Fix/oui clipboard
  client/app/cloud/project/compute/infrastructure/virtualMachine/loginInformation/cloud-project-compute-infrastructure-virtual-machine-login-information.html
  client/app/cloud/project/compute/loadbalancer/configure/compute-loadbalancer-configure.html
  client/app/dbaas/dbaas-metrics/platform/metrics-platform.html
  client/app/dbaas/dbaas-metrics/token/metrics-token.html
  client/app/dbaas/logs/detail/inputs/home/info/logs-inputs-home-info.html
  client/app/deskaas/deskaas-details/deskaas-details.html
  client/app/iplb/modal/failover-ip/iplb-failover-ip-detail.html
  client/app/iplb/modal/nat-ip/iplb-nat-ip-detail.html
  client/app/ui-components/clipboard/clipboard.component.js
  client/app/ui-components/clipboard/clipboard.less
  client/app/vps/modal/shortcut/display-ips/vps-display-ips.html
Labels: enhancement, quality check done

#888 fix(iplb): update switch template
  client/app/iplb/frontends/iplb-frontends.html
  client/app/iplb/serverFarm/iplb-server-farm.html
Labels: bug

#891 fix(config.us.constants): update guide cloud url
  client/app/config/US/common.constants.js
Labels: bug, quality check done

#894 fix(home): display an information about bhs3 maintenance
  client/app/home/home.controller.js
  client/app/home/home.html
  client/app/home/translations/Messages_fr_FR.xml
Labels: bug, quality check done, translation required

#898 fix(cloud.instance): fix collapse button position
  client/app/cloud/project/compute/infrastructure/diagram/cloud-project-compute-infrastructure-diagram.html
Labels: bug, quality check done

#809 feat(nasha): create unavailable page
  client/app/common/phone.constant.js
  client/app/nasha/add/nasha-add.html
  client/app/nasha/add/nasha-add.js
  client/app/nasha/add/nasha-unavailable.controller.js
  client/app/nasha/add/nasha-unavailable.html
  client/app/nasha/add/translations/Messages_fr_FR.xml
  client/components/sidebar/products/nasha-sidebar.service.js
Labels: feature, quality check done, translation required

#873 Refactor/replace cui page header
  client/app/dbaas/dbaas-metrics/header/metrics-header.controller.js
  client/app/dbaas/dbaas-metrics/header/metrics-header.html
  client/app/dbaas/dbaas-metrics/metrics-detail.controller.js
  client/app/dbaas/logs/detail/logs-helper.service.js
  client/app/dbaas/logs/header/logs-dashboard-header.controller.js
  client/app/dbaas/logs/header/logs-dashboard-header.html
  client/app/dbaas/logs/header/logs-list-header.controller.js
  client/app/dbaas/logs/header/logs-list-header.html
  client/app/deskaas/deskaas-details/deskaas-details.html
  client/app/deskaas/deskaas.html
  client/app/iplb/header/iplb-dashboard-header.controller.js
  client/app/iplb/header/iplb-dashboard-header.html
Labels: enhancement, quality check done

#915 Refactor: remove cui-loader
  client/app/ui-components/loader/loader.component.js
Labels: enhancement

#778 fix: fix for oui-datagrid in metrics
  client/app/dbaas/dbaas-metrics/token/metrics-token.controller.js
  client/app/dbaas/dbaas-metrics/token/metrics-token.html
  client/app/dbaas/dbaas-metrics/token/metrics-token.less
  yarn.lock
Labels: enhancement, quality check done

#916 chore(deps): bump ovh-angular-otrs
  package.json
  yarn.lock
Labels: enhancement

#913 refactor(cui-components): remove cui switch and skeleton
  client/app/iplb/vrack/iplb-vrack.html
  client/app/nasha/information/nasha-information.html
  client/app/ui-components/skeleton/skeleton.component.js
  client/app/ui-components/skeleton/skeleton.less
  client/app/ui-components/switch/switch.component.js
Labels: enhancement, ovh-ui-kit, quality check done

#923 fix(vps.upgrade): Remove wrong price information
  client/app/vps/upgrade/vps-upgrade.html
Labels: bug, quality check

#926 fix(ldp): order option broken
  client/app/dbaas/logs/detail/options/home/logs-options-home.controller.js
  client/app/dbaas/logs/detail/options/home/logs-options-home.html
Labels: bug, quality check

#929 chore(build): Install right smarttag
  Makefile
Labels: bug

#912 Refactor: remove cui-labels
  client/app/iplb/vrack/iplb-vrack.html
  client/app/ui-components/labels/labels.component.js
  client/app/ui-components/labels/labels.less
Labels: enhancement, ovh-ui-kit, quality check done

#930 Fix/cui submit cancel button
  client/app/cloud/project/openstack/users/rclone/openstack-users-rclone.modal.html
  client/app/iplb/zone/iplb-zone-add.html
  client/app/iplb/zone/iplb-zone-delete.html
  client/app/ui-components/button/button.component.js
  client/app/vrack/modals/selectVrack.controller.js
  client/app/vrack/modals/selectVrack.html
Labels: enhancement, ovh-ui-kit, quality check done

#942 feat(ldp.index): Add url for kibana webui
  client/app/dbaas/logs/detail/index/logs-index.html
  client/app/dbaas/logs/translations/Messages_fr_FR.xml
Labels: quality check done, translation required
