Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2018-03, with the labels that each got.

#540 Feature/logs input addedit
  client/app/common/translations/Messages_en_GB.xml
  client/app/common/translations/Messages_fr_FR.xml
  client/app/dbaas/logs/detail/inputs/add/configure/logs-inputs-add-configure.controller.js
  client/app/dbaas/logs/detail/inputs/add/configure/logs-inputs-add-configure.html
  client/app/dbaas/logs/detail/inputs/add/configure/logs-inputs-add-configure.less
  client/app/dbaas/logs/detail/inputs/add/configure/logs-inputs-add.constant.js
  client/app/dbaas/logs/detail/inputs/add/configure/translations/Messages_en_GB.xml
  client/app/dbaas/logs/detail/inputs/add/configure/translations/Messages_fr_FR.xml
  client/app/dbaas/logs/detail/inputs/add/edit/logs-inputs-add-edit.constant.js
  client/app/dbaas/logs/detail/inputs/add/edit/logs-inputs-add-edit.controller.js
  client/app/dbaas/logs/detail/inputs/add/edit/logs-inputs-add-edit.html
  client/app/dbaas/logs/detail/inputs/add/edit/translations/Messages_en_GB.xml
  client/app/dbaas/logs/detail/inputs/add/edit/translations/Messages_fr_FR.xml
  client/app/dbaas/logs/detail/inputs/add/logs-inputs-add.controller.js
  client/app/dbaas/logs/detail/inputs/add/logs-inputs-add.html
  client/app/dbaas/logs/detail/inputs/add/logs-inputs-add.less
  client/app/dbaas/logs/detail/inputs/add/networks/logs-inputs-add-networks.controller.js
  client/app/dbaas/logs/detail/inputs/add/networks/logs-inputs-add-networks.html
  client/app/dbaas/logs/detail/inputs/add/networks/logs-inputs-add-networks.less
  client/app/dbaas/logs/detail/inputs/add/networks/translations/Messages_en_GB.xml
  client/app/dbaas/logs/detail/inputs/add/networks/translations/Messages_fr_FR.xml
  client/app/dbaas/logs/detail/inputs/add/translations/Messages_en_GB.xml
  client/app/dbaas/logs/detail/inputs/add/translations/Messages_fr_FR.xml
  client/app/dbaas/logs/detail/inputs/home/logs-inputs-home.controller.js
  client/app/dbaas/logs/detail/inputs/home/logs-inputs-home.html
  client/app/dbaas/logs/detail/inputs/home/translations/Messages_en_GB.xml
  client/app/dbaas/logs/detail/inputs/home/translations/Messages_fr_FR.xml
  client/app/dbaas/logs/detail/inputs/logs-inputs.constant.js
  client/app/dbaas/logs/detail/inputs/logs-inputs.js
  client/app/dbaas/logs/detail/inputs/logs-inputs.service.js
  client/app/dbaas/logs/detail/inputs/translations/Messages_en_GB.xml
  client/app/dbaas/logs/detail/inputs/translations/Messages_fr_FR.xml
  client/app/dbaas/logs/detail/logs-detail.less
  client/app/dbaas/logs/detail/options/logs-options.service.js
  client/app/dbaas/logs/detail/roles/logs-roles.js
  client/app/dbaas/logs/detail/streams/alerts/add/alerts-add.controller.js
  client/app/dbaas/logs/translations/Messages_en_GB.xml
  client/app/helper/controller-helper.service.js
  client/app/ui-components/inline-adder/inline-adder-item.controller.js
  client/app/ui-components/inline-adder/inline-adder-item.html
  client/app/ui-components/inline-adder/inline-adder.component.js
  client/app/ui-components/inline-adder/inline-adder.controller.js
  client/app/ui-components/inline-adder/inline-adder.less
Labels: feature

#546 Feature/new categories
  client/app/cloud/cloud.constants.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/cloud-project-compute-infrastructure-virtualMachine-addEdit.controller.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/cloud-project-compute-infrastructure-virtualMachine-addEdit.html
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/cloud-project-compute-infrastructure-virtualMachine-addEdit.less
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/translations/Messages_fr_FR.xml
Labels: Translation required

#605 fix(novnc): remove unused file
  client/assets/noVNC/.bower.json
  client/assets/noVNC/.bowerrc
  client/assets/noVNC/Gruntfile.js
  client/assets/noVNC/bower.json
  client/assets/noVNC/deploy.sh
  client/assets/noVNC/package.json
Labels: bug, enhancement

#555 feat(iplb): sslCertificate add form component
  client/app/app.js
  client/app/cda/cda.service.js
  client/app/cda/details/home/detail/edit/cda-detail-edit.controller.js
  client/app/cda/details/home/detail/edit/cda-detail-edit.html
  client/app/common/translations/Messages_fr_FR.xml
  client/app/iplb/sslCertificate/iplb-ssl-certificate-edit.html
  client/app/iplb/sslCertificate/order/iplb-ssl-certificate-order.html
Labels: QC_OK, Translation required

#627 added disabled account support in LDP
  client/app/dbaas/logs/detail/home/logs-home-service.js
  client/app/dbaas/logs/detail/home/logs-home.controller.js
  client/app/dbaas/logs/detail/home/logs-home.html
  client/app/dbaas/logs/detail/home/logs-home.js
  client/app/dbaas/logs/detail/home/translations/Messages_en_GB.xml
  client/app/dbaas/logs/detail/logs-detail.js
  client/app/dbaas/logs/detail/logs-helper.service.js
  client/app/dbaas/logs/header/logs-dashboard-header.controller.js
  client/app/dbaas/logs/header/logs-dashboard-header.html
  client/app/dbaas/logs/list/logs-list.service.js
  client/app/ui-components/tabs/tabs.component.js
  client/app/ui-components/tabs/tabs.less
Labels: feature
