Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2018-12, with the labels that each got.

#1217 fix(servers.add-server): region selection color
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.html
Labels: bug, quality check done

#1221 refactor(package.json): use start:eu as default start script
  package.json
Labels: enhancement

#1222 fix(nasha.order): enable order
  client/components/sidebar/products/nasha-sidebar.service.js
Labels: bug, quality check done

#1224 fix(i18n): retrieve translations manually
  client/app/cloud/project/openstack/users/openrc/translations/Messages_de_DE.json
  client/app/cloud/project/openstack/users/openrc/translations/Messages_en_ASIA.json
  client/app/cloud/project/openstack/users/openrc/translations/Messages_en_AU.json
  client/app/cloud/project/openstack/users/openrc/translations/Messages_en_CA.json
  client/app/cloud/project/openstack/users/openrc/translations/Messages_en_GB.json
  client/app/cloud/project/openstack/users/openrc/translations/Messages_en_SG.json
  client/app/cloud/project/openstack/users/openrc/translations/Messages_en_US.json
  client/app/cloud/project/openstack/users/openrc/translations/Messages_es_ES.json
  client/app/cloud/project/openstack/users/openrc/translations/Messages_es_US.json
  client/app/cloud/project/openstack/users/openrc/translations/Messages_it_IT.json
  client/app/cloud/project/openstack/users/openrc/translations/Messages_nl_NL.json
  client/app/cloud/project/openstack/users/openrc/translations/Messages_pl_PL.json
  client/app/cloud/project/openstack/users/openrc/translations/Messages_pt_PT.json
  client/app/vps/translations/Messages_de_DE.json
  client/app/vps/translations/Messages_en_ASIA.json
  client/app/vps/translations/Messages_en_AU.json
  client/app/vps/translations/Messages_en_CA.json
  client/app/vps/translations/Messages_en_GB.json
  client/app/vps/translations/Messages_en_SG.json
  client/app/vps/translations/Messages_en_US.json
  client/app/vps/translations/Messages_es_ES.json
  client/app/vps/translations/Messages_es_US.json
  client/app/vps/translations/Messages_it_IT.json
  client/app/vps/translations/Messages_nl_NL.json
  client/app/vps/translations/Messages_pl_PL.json
  client/app/vps/translations/Messages_pt_PT.json
Labels: bug

#1215 fix(button-alignment): action menu alignment fix
  client/app/cloud/project/billing/rights/cloud-project-billing-rights.html
  client/app/cloud/project/compute/infrastructure/list/cloud-project-compute-infrastructure-list.controller.js
  client/app/cloud/project/compute/infrastructure/list/cloud-project-compute-infrastructure-list.html
  client/app/cloud/project/compute/volume/cloud-project-compute-volume.html
  client/app/cloud/project/openstack/users/openstack-users.html
  client/app/vps/veeam/order/vps-order-veeam.controller.js
Labels: bug, quality check done

#1225 fix(ldp): password validation
  client/app/dbaas/logs/detail/account/password/logs-account-password.html
  client/app/dbaas/logs/detail/account/setup/logs-account-setup.html
Labels: bug, quality check done

#1233 feat(components.navbar): remove some assistance menu items for FR
  client/app/common/translations/Messages_fr_FR.json
  client/components/navbar/navbar.service.js
Labels: bug, quality check, translation required

#1218 Fix IPLB configuration page
  client/app/cloud/project/compute/infrastructure/privateNetwork/translations/Messages_fr_FR.json
  client/app/cloud/project/compute/loadbalancer/translations/Messages_fr_FR.json
  client/app/cloud/project/compute/translations/Messages_fr_FR.json
  client/app/cloud/project/storage/storage-add/translations/Messages_fr_FR.json
  client/app/cloud/project/storage/storage-details/translations/Messages_fr_FR.json
  client/app/cloud/project/storage/translations/Messages_fr_FR.json
  client/app/dbaas/dbaas-metrics/dashboard/translations/Messages_fr_FR.json
  client/app/helper/service-helper.service.js
  client/app/iplb/configuration/iplb-configuration.controller.js
  client/app/iplb/configuration/iplb-configuration.html
  client/app/iplb/configuration/iplb-configuration.js
  client/app/iplb/configuration/iplb-configuration.service.js
  client/app/iplb/configuration/translations/Messages_fr_FR.json
  client/app/iplb/frontends/translations/Messages_fr_FR.json
  client/app/iplb/serverFarm/translations/Messages_fr_FR.json
  client/app/nasha/add/translations/Messages_fr_FR.json
  client/app/veeam/dashboard/translations/Messages_fr_FR.json
  client/app/veeam/translations/Messages_fr_FR.json
  client/app/vps/translations/Messages_fr_FR.json
Labels: bug, quality check done, translation required
