Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2018-05, with the labels that each got.

#554 feat(pci): Add the new VM creation feature
  client/app/cloud/cloud.constants.js
  client/app/cloud/project/compute/infrastructure/diagram/cloud-project-compute-infrastructure-diagram.controller.js
  client/app/cloud/project/compute/infrastructure/diagram/cloud-project-compute-infrastructure-diagram.html
  client/app/cloud/project/compute/infrastructure/flavor.service.js
  client/app/cloud/project/compute/infrastructure/image.service.js
  client/app/cloud/project/compute/infrastructure/list/cloud-project-compute-infrastructure-list.controller.js
  client/app/cloud/project/compute/infrastructure/list/cloud-project-compute-infrastructure-list.html
  client/app/cloud/project/compute/infrastructure/region.service.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.controller.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.html
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.less
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.service.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/translations/Messages_fr_FR.xml
  client/app/ui-components/wizardForm/wizardForm.component.js
  client/app/ui-components/wizardForm/wizardForm.html
  client/assets/images/cloud/os/windows_server_2016_50.png
  client/components/cloud/region/region.service.js
  karma.conf.tpl.js
Labels: feature, quality check required

#480 (WIP) feat (iplb) add vrack configuration to iplb
  client/app/common/OvhPoll.service.js
  client/app/iplb/frontends/iplb-frontends-edit.html
  client/app/iplb/header/iplb-dashboard-header.html
  client/app/iplb/home/iplb-home.controller.js
  client/app/iplb/home/iplb-home.html
  client/app/iplb/home/iplb-home.js
  client/app/iplb/iplb-detail.controller.js
  client/app/iplb/iplb.js
  client/app/iplb/serverFarm/iplb-server-farm-edit.controller.js
  client/app/iplb/serverFarm/iplb-server-farm-edit.html
  client/app/iplb/serverFarm/iplb-server-farm.service.js
  client/app/iplb/serverFarm/probe/iplb-server-farm-probe.html
  client/app/iplb/sslCertificate/order/iplb-ssl-certificate-order.html
  client/app/iplb/vrack/common/iplb-vrack-helper.service.js
  client/app/iplb/vrack/iplb-vrack-edit.controller.js
  client/app/iplb/vrack/iplb-vrack-edit.html
  client/app/iplb/vrack/iplb-vrack.controller.js
  client/app/iplb/vrack/iplb-vrack.html
  client/app/iplb/vrack/iplb-vrack.js
  client/app/iplb/vrack/iplb-vrack.less
  client/app/iplb/vrack/iplb-vrack.service.js
  client/app/oui-less-override.less
  client/app/ui-components/advanced-options/advanced-options.less
  client/app/ui-components/input/key-value.less
  client/app/ui-components/labels/labels.component.js
  client/app/ui-components/labels/labels.less
  client/app/ui-components/radio-bar/radio-bar.less
Labels: feature, quality check done

#731 chore(*): fix mobile display
  client/app/ui-components/tabs/tabs.less
  client/app/ui-components/tile/_mixins.less
  client/app/ui-components/tile/tile.less
Labels: bug

#742 chore(*): upgrade to the lastest version of ovh-api-services
  yarn.lock
Labels: bug

#744 refactor(*): update cui-grid system
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.html
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.less
  client/app/dbaas/logs/detail/offer/logs-offer.html
  client/app/dbaas/logs/detail/options/home/logs-options-home.html
  client/app/ui-components/grid/grid.less
  client/app/ui-components/page/page.less
Labels: enhancement

#752 feat: update otrs
  yarn.lock
Labels: feature, quality check done

#724 Feat/upgrade
  client/app/cloud/project/compute/loadbalancer/configure/compute-loadbalancer-configure.controller.js
  client/app/cloud/project/compute/loadbalancer/configure/compute-loadbalancer-configure.html
  client/app/cloud/project/compute/loadbalancer/configure/compute-loadbalancer-configure.js
  client/app/cloud/project/compute/loadbalancer/translations/Messages_fr_FR.xml
  client/app/deskaas/deskaas-upgrade/deskaas-upgrade.controller.js
  client/app/deskaas/deskaas-upgrade/deskaas-upgrade.html
  client/app/ui-components/clipboard/clipboard.component.js
  client/app/vps/upgrade/vps-upgrade.html
  client/app/vps/upgrade/vps-upgrade.less
Labels: quality check done

#759 fix(navbar): remove labs URL
  client/components/navbar/navbar.service.js
Labels: bug
