Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2019-10, with the labels that each got.

#1580 Feat/enterprise cloud database
  package.json
  yarn.lock
Labels: feature, quality check

#1583 fix: server sidebar version update
  package.json
  yarn.lock
Labels: bug, dependencies

#1590 feat(vps): make user go to IP page and filter with the service name
  client/app/config/all.ca.js
  client/app/config/all.eu.js
  client/app/config/all.us.js
Labels: feature

#1591 fix(ldp): JS error while adding adp role
  client/app/dbaas/logs/detail/roles/members/add/add-members.controller.js
  client/app/dbaas/logs/detail/roles/members/add/add-members.html
Labels: bug, quality check ok

#1593 fix(vps): disable vps section for US
  package.json
  yarn.lock
Labels: bug

#1592 fix(dbaas-logs-inputs): helpers fetch from api
  client/app/dbaas/logs/detail/inputs/add/configure/logs-inputs-add-configure.controller.js
  client/app/dbaas/logs/detail/inputs/add/configure/logs-inputs-add-configure.html
  client/app/dbaas/logs/detail/inputs/logs-inputs.service.js
  client/app/dbaas/logs/logs-constants.js
  client/app/dbaas/logs/translations/Messages_fr_FR.json
Labels: bug, quality check ok

#1598 build: bump @ovh-ux/manager-navbar
  package.json
  yarn.lock
Labels: dependencies
