Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2019-07, with the labels that each got.

#1480 feat(cloud.logs): filebeat 6.8 - 17 modules
  client/app/dbaas/logs/logs-constants.js
Labels: feature, quality check ok

#1498 Release v7.27.0
  client/app/common/translations/Messages_de_DE.json
  client/app/common/translations/Messages_en_ASIA.json
  client/app/common/translations/Messages_en_AU.json
  client/app/common/translations/Messages_en_CA.json
  client/app/common/translations/Messages_en_GB.json
  client/app/common/translations/Messages_en_SG.json
  client/app/common/translations/Messages_en_US.json
  client/app/common/translations/Messages_es_ES.json
  client/app/common/translations/Messages_fi_FI.json
  client/app/common/translations/Messages_it_IT.json
  client/app/common/translations/Messages_lt_LT.json
  client/app/common/translations/Messages_pl_PL.json
  client/app/dbaas/logs/logs-constants.js
  package.json
  yarn.lock
Labels: release :package:

#1497 fix(metrics-tokens-create): handle empty label
  client/app/dbaas/dbaas-metrics/token/add/metrics-token-add.controller.js
Labels: bug, quality check ok

#1502 build(deps): upgrade ovh-api-services to v7.0.0
  package.json
  yarn.lock
Labels: dependencies

#1504 build(deps): upgrade ng-ovh-otrs to v7.1.6
  package.json
  yarn.lock
Labels: bug, dependencies

#1501 Release v7.27.1
  client/app/common/translations/Messages_pt_PT.json
  client/app/dbaas/dbaas-metrics/token/add/metrics-token-add.controller.js
  package.json
  yarn.lock
Labels: release :package:

#1517 fix(logs-data-platform): fix cancel button
  client/app/dbaas/logs/detail/offer/logs-offer.controller.js
  client/app/dbaas/logs/detail/offer/logs-offer.html
Labels: bug, quality check ok

#1503 Ldp improvements 190705
  client/app/dbaas/logs/detail/aliases/logs-aliases.service.js
  client/app/dbaas/logs/detail/dashboards/logs-dashboards.service.js
  client/app/dbaas/logs/detail/home/logs-home.service.js
  client/app/dbaas/logs/detail/index/logs-index.service.js
  client/app/dbaas/logs/detail/inputs/logs-inputs.service.js
  client/app/dbaas/logs/detail/roles/logs-roles.service.js
  client/app/dbaas/logs/detail/streams/alerts/streams-alerts.service.js
  client/app/dbaas/logs/detail/streams/follow/streams-follow.html
  client/app/dbaas/logs/detail/streams/logs-streams.service.js
  client/app/dbaas/logs/logs-constants.js
  client/app/dbaas/logs/translations/Messages_fr_CA.json
  client/app/dbaas/logs/translations/Messages_fr_FR.json
Labels: enhancement, quality check ok

#1516 fix(vps.ip.reverse): use ip call for additional ips
  client/app/vps/import/constants.js
  client/app/vps/import/vps.service.js
Labels: bug, quality check ok

#1520 Release v7.28.0
  client/app/dbaas/logs/detail/aliases/logs-aliases.service.js
  client/app/dbaas/logs/detail/dashboards/logs-dashboards.service.js
  client/app/dbaas/logs/detail/home/logs-home.service.js
  client/app/dbaas/logs/detail/index/logs-index.service.js
  client/app/dbaas/logs/detail/inputs/logs-inputs.service.js
  client/app/dbaas/logs/detail/offer/logs-offer.controller.js
  client/app/dbaas/logs/detail/offer/logs-offer.html
  client/app/dbaas/logs/detail/roles/logs-roles.service.js
  client/app/dbaas/logs/detail/streams/alerts/streams-alerts.service.js
  client/app/dbaas/logs/detail/streams/follow/streams-follow.html
  client/app/dbaas/logs/detail/streams/logs-streams.service.js
  client/app/dbaas/logs/logs-constants.js
  client/app/dbaas/logs/translations/Messages_de_DE.json
  client/app/dbaas/logs/translations/Messages_en_ASIA.json
  client/app/dbaas/logs/translations/Messages_en_AU.json
  client/app/dbaas/logs/translations/Messages_en_CA.json
  client/app/dbaas/logs/translations/Messages_en_GB.json
  client/app/dbaas/logs/translations/Messages_en_SG.json
  client/app/dbaas/logs/translations/Messages_en_US.json
  client/app/dbaas/logs/translations/Messages_fi_FI.json
  client/app/dbaas/logs/translations/Messages_fr_CA.json
  client/app/dbaas/logs/translations/Messages_fr_FR.json
  client/app/dbaas/logs/translations/Messages_lt_LT.json
  client/app/dbaas/logs/translations/Messages_pt_PT.json
  client/app/vps/import/constants.js
  client/app/vps/import/vps.service.js
Labels: release :package:

#1525 fix(dbaas.logs.translations): fix typo in translations
  client/app/dbaas/logs/translations/Messages_fr_FR.json
Labels: bug

#1526 build(deps): upgrade ng-ovh-http to v4.0.2
  package.json
  yarn.lock
Labels: dependencies

#1519 refactor: use ng uirouter layout component
  client/app/app.js
  client/components/angular-ui-router/angular-ui-router.module.js
  package.json
  yarn.lock
Labels: enhancement

#1523 fix(logs-data-platform): fix datagrid skeleton
  client/app/dbaas/dbaas-metrics/token/metrics-token.html
  client/app/dbaas/logs/detail/index/logs-index.html
  client/app/dbaas/logs/list/logs-list.controller.js
  client/app/dbaas/logs/list/logs-list.html
  client/app/iplb/vrack/iplb-vrack.html
  client/app/veeam/storage/veeam-storage.html
Labels: bug, quality check ok

#1527 fix(iplb): fix button in configuration
  client/app/iplb/configuration/iplb-configuration.html
Labels: bug, quality check ok

#1532 build(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies
