Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2019-09, with the labels that each got.

#1567 Remove NL language
  package.json
  yarn.lock
Labels: quality check ok

#1571 feat: add manager banner
  client/app/app.js
  client/app/home/home.html
  package.json
  yarn.lock
Labels: quality check ok

#1565 feat(vps): add vps redirection into legacy section
  client/components/sidebar/products/vps-sidebar.service.js
  client/components/sidebar/sidebar.constants.js
Labels: feature, quality check ok

#1576 fix(vnc): restore vnc client
  client/app/index.js
Labels: bug, quality check ok
