Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2019-08, with the labels that each got.

#1534 fix(cloud.logs): allow to create an index again
  client/app/dbaas/logs/detail/index/logs-index.service.js
Labels: bug, quality check ok

#1535 Release v7.28.2
  client/app/dbaas/logs/detail/index/logs-index.service.js
  client/app/dbaas/logs/translations/Messages_it_IT.json
  client/app/iplb/configuration/iplb-configuration.html
  package.json
  yarn.lock
Labels: release :package:

#1533 fix(veeam.storage): display error message if quota upgrade fails
  client/app/veeam/storage/veeam-storage.controller.js
  client/app/veeam/storage/veeam-storage.html
Labels: bug, quality check ok

#1540 feat: add @ovh-ux/ng-ui-router-line-progress
  client/app/app.js
  client/app/app.less
  client/index.html
  package.json
  yarn.lock
Labels: feature

#1542 fix(database): fix translation
  client/app/common/translations/Messages_fr_FR.json
Labels: bug, quality check ok, translation required

#1544 fix(iplb): quota threshold modal
  client/app/iplb/home/updateQuota/iplb-update-quota.html
  client/app/iplb/translations/Messages_fr_FR.json
Labels: bug, translation required

#1545 fix(sidebar): use nasha from cloud manager
  package.json
  yarn.lock
Labels: bug

#1550 feat: add @ovh-ux/ng-ovh-request-tagger
  package.json
  yarn.lock
Labels: enhancement

#1549 fix(vps): database tab for CA and US
  client/app/vps/cloud-database/vps-cloud-database.routing.js
  client/app/vps/header/vps-header.controller.js
  client/app/vps/header/vps-header.html
Labels: bug, quality check ok

#1552 Release v7.29.1
  client/app/vps/cloud-database/vps-cloud-database.routing.js
  client/app/vps/header/vps-header.controller.js
  client/app/vps/header/vps-header.html
Labels: release :package:

#1555 build(deps): upgrade ng-ovh-sso-auth to v4.2.0
  package.json
  yarn.lock
Labels: dependencies

#1557 fix: remove partners entry from the navbar
  client/app/config/all.eu.js
  client/components/navbar/navbar.service.js
Labels: bug

#1556 feat(vps.agora): handle new refs in special mapping
  client/app/vps/upgrade/vps-upgrade.constants.js
  client/app/vps/upgrade/vps-upgrade.controller.js
Labels: feature, quality check ok

#1558 docs: remove CODE_OF_CONDUCT.md file.
  CODE_OF_CONDUCT.md
Labels: documentation

#1560 Release v7.30.0
  client/app/cda/translations/Messages_es_ES.json
  client/app/common/translations/Messages_es_ES.json
  client/app/iplb/translations/Messages_de_DE.json
  client/app/iplb/translations/Messages_fr_CA.json
  client/app/iplb/translations/Messages_it_IT.json
  client/app/iplb/translations/Messages_pl_PL.json
  client/app/iplb/translations/Messages_pt_PT.json
  client/app/vps/upgrade/vps-upgrade.constants.js
  client/app/vps/upgrade/vps-upgrade.controller.js
  package.json
  yarn.lock
Labels: release :package:

#1562 build(package.json): bump ng-ovh-sso-auth to v4.2.1
  package.json
  yarn.lock
Labels: dependencies
