Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2019-06, with the labels that each got.

#1477 build(package.json): set the right package name
  package.json
Labels: enhancement

#1481 fix(deps): upgrade ng-ovh-otrs to v7.1.4
  package.json
  yarn.lock
Labels: bug

#1483 feat(sidebar): change redirection for kube order
  client/components/sidebar/products/kubernetes-constants.js
  client/components/sidebar/products/kubernetes-sidebar.service.js
Labels: enhancement

#1482 build: bump @ovh-ux/manager-navbar
  client/index.html
  package.json
  yarn.lock
Labels: dependencies

#1485 Release v7.25.10
  client/index.html
  package.json
  yarn.lock
Labels: release :package:

#1488 fix(core): add missing clipboard component translations
  client/app/app.js
  client/app/common/translations/Messages_fr_FR.json
Labels: bug

#1489 fix(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies

#1490 Release v7.25.11
  client/app/app.js
  client/app/common/translations/Messages_fr_FR.json
  package.json
  yarn.lock
Labels: release :package:

#1493 fix(deps): upgrade ng-ovh-otrs to v7.1.5
  package.json
  yarn.lock
Labels: dependencies
