Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2019-05, with the labels that each got.

#1438 fix(vps.snapshot.order.legacy): add missing translations
  client/app/vps/snapshot/order/legacy/vps-snapshot-order-legacy.html
  client/app/vps/snapshot/order/translations/Messages_fr_FR.json
Labels: bug

#1439 fix(kubernetes.nodes): retrieve correctly the associated projects
  client/app/kubernetes/nodes/add/kubernetes-nodes-add.controller.js
  client/app/kubernetes/nodes/kubernetes-nodes.controller.js
  client/app/kubernetes/nodes/kubernetes-nodes.html
  package.json
  yarn.lock
Labels: bug

#1442 fix(components.navbar): display the right label from language menu
  client/components/navbar/navbar.service.js
  yarn.lock
Labels: bug

#1444 feat(sidebar): add link to new manager
  client/components/sidebar/sidebar.constants.js
  client/components/sidebar/sidebar.js
  client/components/sidebar/sidebar.less
  client/components/sidebar/translations/Messages_fr_FR.json
Labels: feature, quality check, translation required

#1445 feat: use server-sidebar
  client/app/app.js
  client/app/app.less
  client/app/app.scss
  client/app/cloud/less/cloud.popover.less
  client/app/common/cloud-main-controller.controller.js
  client/app/common/less/navbar.less
  client/app/index.js
  client/components/manager-preload/manager-preload.config.js
  client/components/navbar/navbar-builder.service.js
  client/components/navbar/navbar-menu-header/index.js
  client/components/navbar/navbar-menu-header/navbar-menu-header.component.html
  client/components/navbar/navbar-menu-header/navbar-menu-header.component.js
  client/components/navbar/navbar-menu-header/navbar-menu-header.html
  client/components/navbar/navbar-notification.service.js
  client/components/navbar/navbar.config.js
  client/components/navbar/navbar.less
  client/components/navbar/navbar.service.js
  client/components/ovh-angular-otrs/ovh-angular-otrs.js
  client/components/sidebar/products/cda-sidebar.service.js
  client/components/sidebar/products/cdn-sidebar.service.js
  client/components/sidebar/products/cloud-db-sidebar.service.js
  client/components/sidebar/products/cloud-desktop-sidebar.service.js
  client/components/sidebar/products/dbaasts-sidebar.service.js
  client/components/sidebar/products/dedicated-cloud-sidebar.service.js
  client/components/sidebar/products/dedicated-server-sidebar.service.js
  client/components/sidebar/products/housing-sidebar.service.js
  client/components/sidebar/products/ip-sidebar.service.js
  client/components/sidebar/products/iplb-sidebar.service.js
  client/components/sidebar/products/kubernetes-sidebar.service.js
  client/components/sidebar/products/license-sidebar.service.js
  client/components/sidebar/products/logs-sidebar.service.js
  client/components/sidebar/products/nas-sidebar.service.js
  client/components/sidebar/products/nasha-sidebar.service.js
  client/components/sidebar/products/project-sidebar.service.js
  client/components/sidebar/products/veeam-enterprise.sidebar.service.js
  client/components/sidebar/products/veeam-sidebar.service.js
  client/components/sidebar/products/vps-sidebar.service.js
  client/components/sidebar/products/vrack-sidebar.service.js
  client/components/sidebar/sections/cloud-desktop-section.service.js
  client/components/sidebar/sections/iaas-section.service.js
  client/components/sidebar/sections/ip-section.service.js
  client/components/sidebar/sections/license-section.service.js
  client/components/sidebar/sections/load-balancer-section.service.js
  client/components/sidebar/sections/logs-section.service.js
  client/components/sidebar/sections/metrics-section.service.js
  client/components/sidebar/sections/paas-section.service.js
  client/components/sidebar/sections/vrack-section.service.js
  client/components/sidebar/sidebar-helper.service.js
  client/components/sidebar/sidebar-order.service.js
  client/components/sidebar/sidebar-products.service.js
  client/components/sidebar/sidebar.config.js
  client/components/sidebar/sidebar.js
  client/components/sidebar/sidebar.less
  client/index.html
  package.json
  yarn.lock
Labels: feature

#1456 feat: change new manager url display
  client/app/common/cloud-main-controller.controller.js
  client/app/common/common.less
  client/app/common/main.constants.js
  client/app/common/translations/Messages_cs_CZ.json
  client/app/common/translations/Messages_de_DE.json
  client/app/common/translations/Messages_en_ASIA.json
  client/app/common/translations/Messages_en_AU.json
  client/app/common/translations/Messages_en_CA.json
  client/app/common/translations/Messages_en_GB.json
  client/app/common/translations/Messages_en_SG.json
  client/app/common/translations/Messages_en_US.json
  client/app/common/translations/Messages_es_ES.json
  client/app/common/translations/Messages_es_US.json
  client/app/common/translations/Messages_fi_FI.json
  client/app/common/translations/Messages_fr_CA.json
  client/app/common/translations/Messages_fr_FR.json
  client/app/common/translations/Messages_it_IT.json
  client/app/common/translations/Messages_lt_LT.json
  client/app/common/translations/Messages_nl_NL.json
  client/app/common/translations/Messages_pl_PL.json
  client/app/common/translations/Messages_pt_PT.json
  client/components/sidebar/sidebar.js
  client/index.html
  yarn.lock
Labels: enhancement, translation required

#1460 Take service.createdAt in account for consumption chart
  client/app/dbaas/logs/detail/home/logs-home.service.js
Labels: bug, quality check ok

#1465 fix(components.translate): remove duplicate service
  client/components/translate/translate.constants.js
  client/components/translate/translate.service.js
Labels: bug, quality check

#1469 build: bump manager-navbar to v0.5.0
  package.json
  yarn.lock
Labels: bug

#1475 fix(deps): upgrade manager-server-sidebar to 0.1.6
  package.json
  yarn.lock
Labels: bug
