Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2019-03, with the labels that each got.

#1334 fix(flavor): t1 180 flavor
  client/app/cloud/project/compute/infrastructure/flavor.service.js
Labels: bug, quality check ok

#1366 fix(cloud): update wrong cuc directive
  client/app/cloud/project/compute/infrastructure/ip/add_OLD_/cloud-project-compute-infrastructure-ip-add.html
Labels: bug

#1373 fix(dbass.logs.detail.home.capped): add missing cuc prefix
  client/app/dbaas/logs/detail/home/capped/logs-home-capped.controller.js
  client/app/dbaas/logs/detail/home/capped/logs-home-capped.modal.controller.js
Labels: bug

#1357 fix(deps): upgrade ng-ovh-swimming-poll to v4.0.0
  client/app/app.js
  client/app/index.js
  package.json
  yarn.lock
Labels: enhancement, one-manager, quality check ok

#1359 fix(translation): consistant words accross website, order and manager
  client/app/vps/translations/Messages_fr_FR.json
Labels: bug, quality check ok, translation required

#1379 fix(cloud-logs): mobile menu
  client/components/navbar/navbar.service.js
Labels: bug, quality check ok

#1369 build(deps): upgrade ng-ovh-api-wrappers
  client/app/app.js
  package.json
  yarn.lock
Labels: enhancement, quality check ok

#1377 feat(tracking-cloud): track manager cloud
  client/app/cloud/cloud.constants.js
  client/app/cloud/project/cloud-project.controller.js
  client/app/cloud/project/cloud-project.html
  client/app/cloud/project/onboarding/onboarding-pci.controller.js
  client/app/cloud/project/onboarding/onboarding-pci.html
  package.json
  yarn.lock
Labels: enhancement, quality check ok

#1380 fix(deps): upgrade ng-at-internet to v4.0.0
  client/app/app.js
  client/app/index.js
  package.json
  yarn.lock
Labels: enhancement, one-manager, quality check ok

#1381 fix(pci-regions): replace region service
  client/app/cloud/project/compute/infrastructure/diagram/cloud-project-compute-infrastructure-diagram.html
  client/app/cloud/project/compute/infrastructure/list/cloud-project-compute-infrastructure-list.html
  client/components/cloud/project/billing/archive-storage-list/billing-archive-storage-list.component.html
  client/components/cloud/project/billing/details-popover/instance-details-popover.html
  client/components/cloud/project/billing/details-popover/volume-details-popover.html
  client/components/cloud/project/billing/instance-list/billing-instance-list.component.html
  client/components/cloud/project/billing/object-storage-list/billing-object-storage-list.component.html
  client/components/cloud/project/billing/outgoing-trafic/outgoing-trafic.component.html
  client/components/cloud/project/billing/snapshot-list/billing-snapshot-list.component.html
Labels: bug, quality check ok

#1370 fix(order): display doing message when create order
  package.json
  yarn.lock
Labels: bug, one-manager, quality check ok

#1390 fix(deps): upgrade ovh-api-services to v6.1.2
  package.json
  yarn.lock
Labels: bug

#1396 fix(kubernetes): display modals
  client/app/kubernetes/service/kubernetes-service.controller.js
  client/app/kubernetes/service/update/kubernetes-service-update.controller.js
  client/app/kubernetes/service/update/kubernetes-service-update.modal.controller.js
  client/app/kubernetes/service/upgrade-policy/kubernetes-service-upgrade-policy.controller.js
Labels: bug

#1395 feat(kube): add terminate cluster
  client/app/kubernetes/kubernetes.constants.js
  client/app/kubernetes/kubernetes.service.js
  client/app/kubernetes/service/kubernetes-service.controller.js
  client/app/kubernetes/service/kubernetes-service.html
  client/app/kubernetes/service/kubernetes-service.routes.js
  client/app/kubernetes/service/terminate/kubernetes-service-terminate.controller.js
  client/app/kubernetes/service/terminate/kubernetes-service-terminate.html
  client/app/kubernetes/service/terminate/kubernetes-service-terminate.modal.controller.js
  client/app/kubernetes/translations/Messages_fr_FR.json
  package.json
  yarn.lock
Labels: quality check ok, translation required

#1378 feat(usage): additional services price
  client/app/cloud/components/project/billing/additional-services/additional-services.component.controller.js
  client/app/cloud/components/project/billing/additional-services/additional-services.component.html
  client/app/cloud/components/project/billing/additional-services/additional-services.component.js
  client/app/cloud/components/project/billing/hourly-resource-list/billing-hourly-resource-list.component.controller.js
  client/app/cloud/components/project/billing/hourly-resource-list/billing-hourly-resource-list.component.html
  client/app/cloud/components/project/billing/monthly-resource-list/billing-monthly-resource-list.component.html
  client/app/cloud/components/project/billing/outgoing-trafic/outgoing-trafic.component.html
  client/app/cloud/components/project/billing/translations/Messages_fr_FR.json
  client/app/cloud/project/billing/cloud-project-billing.service.js
Labels: feature, quality check ok, translation required

#1393 fix(servers-storage): loader visibility
  client/app/cloud/project/storage/storage.html
Labels: bug, quality check ok

#1324 fix(translation): t1-180 flavor
  client/app/cloud/project/compute/infrastructure/diagram/cloud-project-compute-infrastructure-diagram.controller.js
  client/app/cloud/project/compute/infrastructure/diagram/cloud-project-compute-infrastructure-diagram.html
  client/app/cloud/project/compute/infrastructure/flavor.service.js
  client/app/cloud/project/compute/infrastructure/list/cloud-project-compute-infrastructure-list.controller.js
  client/app/cloud/project/compute/infrastructure/translations/Messages_fr_FR.json
  client/app/cloud/project/compute/infrastructure/translations/Messages_it_IT.json
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.html
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/cloud-project-compute-infrastructure-virtualMachine-addEdit.controller.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/cloud-project-compute-infrastructure-virtualMachine-addEdit.html
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/translations/Messages_fr_FR.json
Labels: bug, quality check ok, translation required

#1385 feat(regions): show inactive regions
  client/app/app.scss
  client/app/cloud/cloud.less
  client/app/cloud/project/compute/infrastructure/cloud-project-compute-infrastructure.js
  client/app/cloud/project/compute/infrastructure/diagram/cloud-project-compute-infrastructure-diagram.js
  client/app/cloud/project/compute/infrastructure/region.service.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.controller.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.html
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/cloud-project-compute-infrastructure-virtualMachine-addEdit.controller.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/cloud-project-compute-infrastructure-virtualMachine-addEdit.html
  client/app/cloud/project/compute/infrastructure/volume/addEdit/cloud-project-compute-infrastructure-volume-addEdit.controller.js
  client/app/cloud/project/compute/infrastructure/volume/addEdit/cloud-project-compute-infrastructure-volume-addEdit.html
  client/app/cloud/project/compute/quota/cloud-project-compute-quota.controller.js
  client/app/cloud/project/compute/quota/cloud-project-compute-quota.html
  client/app/cloud/project/compute/quota/cloud-project-compute-quota.js
  client/app/cloud/project/compute/regions/translations/Messages_fr_FR.json
  client/app/cloud/project/storage/storage-add/storage/add-storage-controller.js
  client/app/cloud/project/storage/storage-add/storage/step_region/add-storage-step-region.html
  client/app/cloud/project/storage/storage.js
Labels: enhancement, quality check ok, translation required

#1407 fix(pci): servers are not loaded in list view
  client/app/cloud/project/compute/infrastructure/list/cloud-project-compute-infrastructure-list.controller.js
Labels: bug, quality check

#1410 Bugfix/launch t1 180 win
  client/app/cloud/project/compute/infrastructure/flavor.service.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/addEdit/cloud-project-compute-infrastructure-virtualMachine-addEdit.controller.js
Labels: bug, quality check ok
