Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2019-01, with the labels that each got.

#1244 build(eslint): use eslint-formatter-pretty
  package.json
  yarn.lock
Labels: enhancement

#1243 fix(cloud.privatenetwork): apply right default loader state
  client/app/cloud/project/compute/infrastructure/privateNetwork/cloud-project-compute-infrastructure-privateNetwork-list.directive.js
Labels: bug, quality check

#1245 refactor(babel): remove unused configuration and dependencies
  .babelrc
  package.json
  yarn.lock
Labels: enhancement

#1240 Feat/vrack automation
  client/app/cloud/project/compute/infrastructure/privateNetwork/cloud-project-compute-infrastructure-privateNetwork-list.directive.js
  client/app/cloud/project/compute/infrastructure/privateNetwork/cloud-project-compute-infrastructure-privateNetwork-list.html
  client/app/cloud/project/compute/infrastructure/privateNetwork/translations/Messages_fr_FR.json
  client/app/vrack/modals/selectVrack.controller.js
  client/app/vrack/modals/translations/Messages_fr_FR.json
  client/app/vrack/vrack.service.js
Labels: feature, quality check ok, translation required

#1241 feat(kubernetes): rename option
  client/app/kubernetes/kubernetes.constants.js
  client/app/kubernetes/kubernetes.controller.js
  client/app/kubernetes/kubernetes.html
  client/app/kubernetes/kubernetes.service.js
  client/app/kubernetes/service/kubernetes-service.controller.js
  client/app/kubernetes/service/kubernetes-service.html
  client/app/kubernetes/translations/Messages_fr_FR.json
Labels: feature, quality check ok, translation required

#1242 feat: support APAC region in PCI
  client/app/app.less
  client/app/cloud/project/compute/cloud-project-compute.html
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.html
  client/app/cloud/project/compute/regions/regions.controller.js
  client/app/cloud/project/compute/regions/regions.html
  client/app/cloud/project/compute/regions/regions.js
  client/app/cloud/project/compute/regions/regions.less
  client/app/cloud/project/compute/regions/translations/Messages_fr_FR.json
  client/components/sidebar/translations/Messages_fr_FR.json
  package.json
  yarn.lock
Labels: feature, quality check ok, translation required

#1249 fix(cloud.logs): translation & ux updates
  client/app/dbaas/logs/detail/aliases/logs-aliases.service.js
  client/app/dbaas/logs/detail/home/formatsports/logs-home-formatsports.html
  client/app/dbaas/logs/detail/home/logs-home.controller.js
  client/app/dbaas/logs/detail/home/logs-home.html
  client/app/dbaas/logs/detail/index/logs-index.controller.js
  client/app/dbaas/logs/detail/index/logs-index.html
  client/app/dbaas/logs/detail/index/logs-index.service.js
  client/app/dbaas/logs/detail/inputs/add/configure/logs-inputs-add-configure.html
  client/app/dbaas/logs/detail/inputs/console/logs-inputs-console.html
  client/app/dbaas/logs/detail/logs-helper.service.js
  client/app/dbaas/logs/detail/roles/edit-permissions/edit-permissions.html
  client/app/dbaas/logs/detail/roles/members/logs-roles-members.html
  client/app/dbaas/logs/detail/streams/add/logs-streams-add.html
  client/app/dbaas/logs/detail/streams/alerts/add/alerts-add.html
  client/app/dbaas/logs/detail/streams/archives/streams-archives.html
  client/app/dbaas/logs/detail/streams/follow/streams-follow.html
  client/app/dbaas/logs/logs-constants.js
  client/app/dbaas/logs/translations/Messages_cs_CZ.json
  client/app/dbaas/logs/translations/Messages_de_DE.json
  client/app/dbaas/logs/translations/Messages_en_ASIA.json
  client/app/dbaas/logs/translations/Messages_en_AU.json
  client/app/dbaas/logs/translations/Messages_en_CA.json
  client/app/dbaas/logs/translations/Messages_en_GB.json
  client/app/dbaas/logs/translations/Messages_en_SG.json
  client/app/dbaas/logs/translations/Messages_en_US.json
  client/app/dbaas/logs/translations/Messages_es_ES.json
  client/app/dbaas/logs/translations/Messages_es_US.json
  client/app/dbaas/logs/translations/Messages_fi_FI.json
  client/app/dbaas/logs/translations/Messages_fr_CA.json
  client/app/dbaas/logs/translations/Messages_fr_FR.json
  client/app/dbaas/logs/translations/Messages_it_IT.json
  client/app/dbaas/logs/translations/Messages_lt_LT.json
  client/app/dbaas/logs/translations/Messages_nl_NL.json
  client/app/dbaas/logs/translations/Messages_pl_PL.json
  client/app/dbaas/logs/translations/Messages_pt_PT.json
Labels: bug, quality check ok

#1250 fix(cloud.logs): update some translations and improve ui (#1249)
  client/app/dbaas/logs/detail/aliases/logs-aliases.service.js
  client/app/dbaas/logs/detail/home/formatsports/logs-home-formatsports.html
  client/app/dbaas/logs/detail/home/logs-home.controller.js
  client/app/dbaas/logs/detail/home/logs-home.html
  client/app/dbaas/logs/detail/index/logs-index.controller.js
  client/app/dbaas/logs/detail/index/logs-index.html
  client/app/dbaas/logs/detail/index/logs-index.service.js
  client/app/dbaas/logs/detail/inputs/add/configure/logs-inputs-add-configure.html
  client/app/dbaas/logs/detail/inputs/console/logs-inputs-console.html
  client/app/dbaas/logs/detail/logs-helper.service.js
  client/app/dbaas/logs/detail/roles/edit-permissions/edit-permissions.html
  client/app/dbaas/logs/detail/roles/members/logs-roles-members.html
  client/app/dbaas/logs/detail/streams/add/logs-streams-add.html
  client/app/dbaas/logs/detail/streams/alerts/add/alerts-add.html
  client/app/dbaas/logs/detail/streams/archives/streams-archives.html
  client/app/dbaas/logs/detail/streams/follow/streams-follow.html
  client/app/dbaas/logs/logs-constants.js
  client/app/dbaas/logs/translations/Messages_cs_CZ.json
  client/app/dbaas/logs/translations/Messages_de_DE.json
  client/app/dbaas/logs/translations/Messages_en_ASIA.json
  client/app/dbaas/logs/translations/Messages_en_AU.json
  client/app/dbaas/logs/translations/Messages_en_CA.json
  client/app/dbaas/logs/translations/Messages_en_GB.json
  client/app/dbaas/logs/translations/Messages_en_SG.json
  client/app/dbaas/logs/translations/Messages_en_US.json
  client/app/dbaas/logs/translations/Messages_es_ES.json
  client/app/dbaas/logs/translations/Messages_es_US.json
  client/app/dbaas/logs/translations/Messages_fi_FI.json
  client/app/dbaas/logs/translations/Messages_fr_CA.json
  client/app/dbaas/logs/translations/Messages_fr_FR.json
  client/app/dbaas/logs/translations/Messages_it_IT.json
  client/app/dbaas/logs/translations/Messages_lt_LT.json
  client/app/dbaas/logs/translations/Messages_nl_NL.json
  client/app/dbaas/logs/translations/Messages_pl_PL.json
  client/app/dbaas/logs/translations/Messages_pt_PT.json
Labels: bug, quality check ok

#1256 fix(server-vm-add): option to hide unavailable flavors
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.html
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/translations/Messages_fr_FR.json
Labels: enhancement, quality check ok, translation required

#1257 fix(cloud.project.storage): ui revamp
  client/app/cloud/project/storage/storage-add/storage/step_container_type/add-storage-step-container-type-controller.js
  client/app/cloud/project/storage/storage-add/storage/step_container_type/add-storage-step-container-type.html
  client/app/cloud/project/storage/storage-add/storage/step_region/add-storage-step-region-controller.js
  client/app/cloud/project/storage/storage-add/storage/step_region/add-storage-step-region.html
  package.json
  yarn.lock
Labels: bug

#1261 fix(pci-tracking): track steps of create server
  client/app/cloud/project/add/cloud-project-add.controller.js
  client/app/cloud/project/add/cloud-project-add.html
  client/app/cloud/project/add/cloud-project-add.less
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.controller.js
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/cloud-project-compute-infrastructure-virtualMachine-add.html
Labels: enhancement, quality check ok

#1255 feat(pci-menu): PCI menu entries revamp
  client/app/app.less
  client/app/cloud/project/billing/cloud-project-billing.html
  client/app/cloud/project/billing/vouchers/cloud-project-billing-vouchers.html
  client/app/cloud/project/cloud-project.controller.js
  client/app/cloud/project/cloud-project.html
  client/app/cloud/project/cloud-project.js
  client/app/cloud/project/cloud-project.less
  client/app/cloud/project/compute/cloud-project-compute.html
  client/app/cloud/project/compute/translations/Messages_fr_FR.json
  client/app/cloud/project/onboarding/onboarding-pci.controller.js
  client/app/cloud/project/onboarding/onboarding-pci.html
  client/app/cloud/project/onboarding/onboarding-pci.less
  client/app/cloud/project/onboarding/translations/Messages_fr_FR.json
  client/app/cloud/project/translations/Messages_fr_FR.json
  client/assets/images/onboarding/compute-storage_uk.jpg
  client/assets/images/onboarding/gestion-tech-admin_uk.jpg
  client/assets/images/onboarding/openstack.jpg
  client/assets/images/onboarding/pay-as-you-go.jpg
  client/components/navbar/navbar.service.js
  client/components/sidebar/products/project-sidebar.service.js
Labels: feature, quality check ok, translation required
