Repository ovh-ux/ovh-manager-cloud, pull requests merged in 2019-04, with the labels that each got.

#1414 translations corrections: fixed negation & typo
  client/app/cloud/project/compute/infrastructure/virtualMachine/add/translations/Messages_de_DE.json
Labels: bug, good first issue, translation required

#1399 fix(pci.ip): add alert message when no pci instance
  client/app/cloud/project/compute/infrastructure/ip/failover/buy/cloud-project-compute-infrastructure-ip-failover-buy.controller.js
  client/app/cloud/project/compute/infrastructure/ip/failover/buy/cloud-project-compute-infrastructure-ip-failover-buy.html
Labels: bug, quality check ok

#1382 fix(pci-usage): replace tables with datagrid
  client/app/app.less
  client/app/cloud/components/project/billing/archive-storage-list/billing-archive-storage-list.component.html
  client/app/cloud/components/project/billing/details-popover/details-popover.controller.js
  client/app/cloud/components/project/billing/details-popover/details-popover.less
  client/app/cloud/components/project/billing/details-popover/details-popover.service.js
  client/app/cloud/components/project/billing/details-popover/instance-details-popover.html
  client/app/cloud/components/project/billing/details-popover/volume-details-popover.html
  client/app/cloud/components/project/billing/hourly-resource-list/billing-hourly-resource-list.component.controller.js
  client/app/cloud/components/project/billing/hourly-resource-list/billing-hourly-resource-list.component.html
  client/app/cloud/components/project/billing/instance-list/billing-instance-list.component.controller.js
  client/app/cloud/components/project/billing/instance-list/billing-instance-list.component.html
  client/app/cloud/components/project/billing/monthly-resource-list/billing-monthly-resource-list.component.controller.js
  client/app/cloud/components/project/billing/monthly-resource-list/billing-monthly-resource-list.component.html
  client/app/cloud/components/project/billing/object-storage-list/billing-object-storage-list.component.html
  client/app/cloud/components/project/billing/outgoing-trafic/outgoing-trafic.component.html
  client/app/cloud/components/project/billing/snapshot-list/billing-snapshot-list.component.html
  client/app/cloud/components/project/billing/volume-list/billing-volume-list.component.controller.js
  client/app/cloud/components/project/billing/volume-list/billing-volume-list.component.html
  client/app/cloud/project/billing/cloud-project-billing.less
Labels: bug, quality check ok

#1418 Update contributing
  CONTRIBUTING.md
Labels: enhancement

#1420 fix(vps.monitoring): safely access to the monitoring data
  client/app/vps/monitoring/vps-monitoring.controller.js
Labels: bug

#1423 feat(chatbot): open the chatbot from the assistance menu
  client/app/app.js
  client/app/common/translations/Messages_fr_FR.json
  client/components/navbar/navbar.service.js
  client/index.html
  package.json
  yarn.lock
Labels: feature, quality check ok

#1427 build(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: enhancement

#1419 feat(cloud.logs): new coldstorage options
  client/app/dbaas/logs/detail/inputs/logs-inputs.service.js
  client/app/dbaas/logs/detail/streams/add/logs-streams-add.controller.js
  client/app/dbaas/logs/detail/streams/add/logs-streams-add.html
  client/app/dbaas/logs/detail/streams/alerts/add/alerts-add.html
  client/app/dbaas/logs/detail/streams/alerts/home/alerts-home.controller.js
  client/app/dbaas/logs/detail/streams/alerts/home/alerts-home.html
  client/app/dbaas/logs/detail/streams/logs-streams.service.js
  client/app/dbaas/logs/logs-constants.js
  client/app/dbaas/logs/translations/Messages_cs_CZ.json
  client/app/dbaas/logs/translations/Messages_de_DE.json
  client/app/dbaas/logs/translations/Messages_en_ASIA.json
  client/app/dbaas/logs/translations/Messages_en_AU.json
  client/app/dbaas/logs/translations/Messages_en_CA.json
  client/app/dbaas/logs/translations/Messages_en_GB.json
  client/app/dbaas/logs/translations/Messages_en_SG.json
  client/app/dbaas/logs/translations/Messages_en_US.json
  client/app/dbaas/logs/translations/Messages_es_ES.json
  client/app/dbaas/logs/translations/Messages_es_US.json
  client/app/dbaas/logs/translations/Messages_fi_FI.json
  client/app/dbaas/logs/translations/Messages_fr_CA.json
  client/app/dbaas/logs/translations/Messages_fr_FR.json
  client/app/dbaas/logs/translations/Messages_it_IT.json
  client/app/dbaas/logs/translations/Messages_lt_LT.json
  client/app/dbaas/logs/translations/Messages_nl_NL.json
  client/app/dbaas/logs/translations/Messages_pl_PL.json
  client/app/dbaas/logs/translations/Messages_pt_PT.json
Labels: feature, quality check ok

#1433 fix(components.navbar): remove duplicate ticket entry
  client/app/common/translations/Messages_fr_FR.json
  client/components/navbar/navbar.service.js
Labels: bug, quality check ok

#1434 add image for dataiku app
  client/app/cloud/project/compute/infrastructure/image.service.js
  client/assets/images/cloud/apps/dataiku.png
Labels: feature
